import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, TextInput } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Text, View } from '@/components/Themed';
import { BorderRadius, Colors, Spacing } from '@/constants/DesignTokens';
import { supportApi } from '@/lib/api';

const reasons = [['reward_not_honoured','Reward not honoured'],['code_failed','Code failed'],['merchant_closed','Merchant was closed'],['offer_differed','Offer differed'],['purchase_problem','Purchase problem'],['other','Something else']] as const;

export default function CommerceIssueScreen() {
  const { receiptId, product } = useLocalSearchParams<{ receiptId: string; product?: string }>();
  const [reason,setReason]=useState('reward_not_honoured'); const [message,setMessage]=useState(''); const [submitting,setSubmitting]=useState(false);
  const submit=async()=>{if(!message.trim()) return Alert.alert('Add details','Tell us what happened so the merchant can respond.'); setSubmitting(true); try { const result=await supportApi.createCommerceCase({receipt_id:String(receiptId),reason,message:message.trim(),evidence:[]}); Alert.alert('Case submitted',`Case ${result.ticket.id.slice(0,8)} is now with the merchant. A response is due within 18 hours.`,[{text:'Done',onPress:()=>router.back()}]); } catch(error){Alert.alert('Case not submitted',error instanceof Error?error.message:'Please try again.');} finally{setSubmitting(false);}};
  return <View style={s.screen}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={22} color={Colors.white}/></Pressable><Text style={s.headerTitle}>REPORT PROBLEM</Text></View><ScrollView contentContainerStyle={s.content}><Text style={s.step}>STEP 1 OF 4 · RECEIPT ATTACHED</Text><Text style={s.title}>What went wrong?</Text><Text style={s.product}>{product || 'Promorang commerce'} · #{String(receiptId).slice(0,8)}</Text><View style={s.reasons}>{reasons.map(([id,label])=><Pressable key={id} onPress={()=>setReason(id)} style={[s.reason,reason===id&&s.reasonActive]}><Text style={s.reasonText}>{label}</Text><Ionicons name={reason===id?'checkmark-circle':'ellipse-outline'} size={20} color={reason===id?Colors.primary:Colors.gray[600]}/></Pressable>)}</View><Text style={s.label}>WHAT HAPPENED?</Text><TextInput multiline maxLength={500} value={message} onChangeText={setMessage} placeholder="What did staff say, and what was the immediate consequence?" placeholderTextColor={Colors.gray[600]} style={s.input}/><View style={s.notice}><Ionicons name="time-outline" size={18} color={Colors.primary}/><Text style={s.noticeText}>The merchant receives the receipt details and your account. Their response is due within 18 hours; Promorang keeps the case history.</Text></View><Pressable disabled={submitting} onPress={submit} style={[s.submit,submitting&&s.disabled]}>{submitting?<ActivityIndicator color={Colors.black}/>:<Text style={s.submitText}>Submit case</Text>}</Pressable></ScrollView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.black},header:{paddingTop:18,paddingHorizontal:Spacing.container,paddingBottom:14,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:Colors.black},back:{width:42,height:42,borderRadius:21,backgroundColor:Colors.gray[900],alignItems:'center',justifyContent:'center'},headerTitle:{color:Colors.white,fontWeight:'900',letterSpacing:.8},content:{padding:Spacing.container,paddingBottom:60},step:{color:Colors.primary,fontFamily:'SpaceMono',fontSize:10,letterSpacing:.8},title:{color:Colors.white,fontSize:32,fontWeight:'900',marginTop:12},product:{color:Colors.gray[400],fontSize:12,marginTop:6},reasons:{marginTop:20,gap:8,backgroundColor:'transparent'},reason:{minHeight:52,borderRadius:14,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.gray[900],paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},reasonActive:{borderColor:Colors.primary},reasonText:{color:Colors.white,fontSize:13,fontWeight:'800'},label:{color:Colors.gray[400],fontSize:10,fontWeight:'900',letterSpacing:.8,marginTop:24,marginBottom:8},input:{minHeight:130,borderRadius:BorderRadius.xl,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.gray[900],color:Colors.white,padding:15,textAlignVertical:'top',fontSize:13},notice:{marginTop:14,borderRadius:14,padding:13,flexDirection:'row',gap:9,backgroundColor:Colors.ambientWash},noticeText:{flex:1,color:Colors.gray[300],fontSize:11,lineHeight:16},submit:{marginTop:20,minHeight:52,borderRadius:18,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'},submitText:{color:Colors.black,fontSize:14,fontWeight:'900'},disabled:{opacity:.55}});
