import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Share, StyleSheet, TextInput } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Text, View } from '@/components/Themed';
import { BorderRadius, Colors, Spacing } from '@/constants/DesignTokens';
import { guestRsvpApi, WEB_BASE } from '@/lib/api';

export default function GuestRsvpScreen() {
  const { momentId, title } = useLocalSearchParams<{ momentId: string; title?: string }>();
  const [form, setForm] = useState({ full_name: '', mobile: '', email: '', guest_count: 1, group_name: '', meeting_point: '', consent_whatsapp: true });
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<any>(null);
  const openPass = () => router.replace({ pathname: '/guest-pass/[token]', params: { token: result.rsvp.invite_token, manageToken: result.rsvp.manage_token } } as any);
  const submit = async () => {
    if (!form.full_name.trim() || form.mobile.trim().length < 7) return Alert.alert('Add your details', 'Full name and mobile number are required.');
    setBusy(true);
    try { setResult(await guestRsvpApi.create({ ...form, moment_id: momentId })); }
    catch (error) { Alert.alert('Could not reserve', error instanceof Error ? error.message : 'Please try again.'); }
    finally { setBusy(false); }
  };
  if (result) {
    const url = `${WEB_BASE}/guest-pass/${result.rsvp.invite_token}`;
    return <View style={s.screen}><ScrollView contentContainerStyle={s.content}><View style={s.pass}><Text style={s.passBrand}>PROMORANG GUEST PASS</Text><Text style={s.passTitle}>YOU’RE GOING</Text><Text style={s.passMoment}>{result.moment.title}</Text><View style={s.rule}/><Text style={s.code}>{result.rsvp.pass_code}</Text><Text style={s.passMeta}>{result.rsvp.guest_count} {result.rsvp.guest_count === 1 ? 'place' : 'places'} held</Text></View><Pressable style={s.whatsapp} onPress={() => Share.share({ message: `Join my group for ${result.moment.title}: ${url}` })}><Ionicons name="logo-whatsapp" size={20} color={Colors.black}/><Text style={s.primaryText}>Invite your group</Text></Pressable><Pressable style={s.secondary} onPress={openPass}><Text style={s.secondaryText}>Open my private guest pass</Text></Pressable></ScrollView></View>;
  }
  return <View style={s.screen}><View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><Ionicons name="chevron-back" size={22} color={Colors.white}/></Pressable><Text style={s.headerTitle}>RESERVE YOUR PLACE</Text></View><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>NO ACCOUNT REQUIRED</Text><Text style={s.title}>{title || 'Join this Moment'}</Text><Text style={s.subtitle}>Hold space for your crew. We use your mobile number only for confirmation and operational updates you choose.</Text>{[['Full name','full_name'],['Mobile / WhatsApp','mobile'],['Email · optional','email'],['Group name · optional','group_name'],['Meeting point · optional','meeting_point']].map(([label,key]) => <View key={key} style={s.field}><Text style={s.label}>{label.toUpperCase()}</Text><TextInput value={(form as any)[key]} onChangeText={(value) => setForm({ ...form, [key]: value })} style={s.input} placeholderTextColor={Colors.gray[600]}/></View>)}<Text style={s.label}>NUMBER OF PEOPLE · INCLUDING YOU</Text><View style={s.counter}><Pressable onPress={() => setForm({ ...form, guest_count: Math.max(1, form.guest_count - 1) })}><Ionicons name="remove" size={20} color={Colors.white}/></Pressable><Text style={s.count}>{form.guest_count}</Text><Pressable onPress={() => setForm({ ...form, guest_count: Math.min(12, form.guest_count + 1) })}><Ionicons name="add" size={20} color={Colors.white}/></Pressable></View><Pressable disabled={busy} onPress={submit} style={s.submit}>{busy ? <ActivityIndicator color={Colors.black}/> : <><Text style={s.primaryText}>Confirm RSVP</Text><Ionicons name="arrow-forward" size={18} color={Colors.black}/></>}</Pressable></ScrollView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.black},header:{paddingTop:18,paddingHorizontal:Spacing.container,paddingBottom:14,flexDirection:'row',alignItems:'center',gap:12,backgroundColor:Colors.black},back:{width:42,height:42,borderRadius:21,backgroundColor:Colors.gray[900],alignItems:'center',justifyContent:'center'},headerTitle:{color:Colors.white,fontWeight:'900'},content:{padding:Spacing.container,paddingBottom:60},eyebrow:{color:Colors.primary,fontFamily:'SpaceMono',fontSize:10,letterSpacing:1},title:{color:Colors.white,fontSize:34,lineHeight:38,fontWeight:'900',marginTop:12},subtitle:{color:Colors.gray[400],fontSize:12,lineHeight:18,marginTop:10,marginBottom:14},field:{marginTop:13,backgroundColor:'transparent'},label:{color:Colors.gray[400],fontSize:9,fontWeight:'900',letterSpacing:.8,marginTop:14,marginBottom:6},input:{height:48,borderRadius:14,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.gray[900],color:Colors.white,paddingHorizontal:13},counter:{width:150,height:48,borderRadius:14,backgroundColor:Colors.gray[900],flexDirection:'row',alignItems:'center',justifyContent:'space-around'},count:{color:Colors.white,fontSize:18,fontWeight:'900'},submit:{marginTop:24,height:52,borderRadius:18,backgroundColor:Colors.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},primaryText:{color:Colors.black,fontSize:14,fontWeight:'900'},pass:{marginTop:40,padding:22,backgroundColor:'#f4ead8',borderTopWidth:1,borderBottomWidth:1,borderStyle:'dashed',borderColor:'rgba(0,0,0,.3)'},passBrand:{color:Colors.primary,fontFamily:'SpaceMono',fontSize:9,letterSpacing:1},passTitle:{color:'#17130f',fontSize:38,fontWeight:'900',marginTop:8},passMoment:{color:'#17130f',fontSize:16,fontWeight:'800',marginTop:4},rule:{height:1,backgroundColor:'rgba(0,0,0,.16)',marginVertical:18},code:{color:'#17130f',fontFamily:'SpaceMono',fontSize:23,fontWeight:'900'},passMeta:{color:'rgba(0,0,0,.55)',fontSize:11,marginTop:7},whatsapp:{marginTop:18,height:52,borderRadius:18,backgroundColor:'#25D366',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},secondary:{marginTop:10,height:50,borderRadius:18,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{color:Colors.white,fontWeight:'800'}});
