import { ActivityIndicator, ImageBackground, ScrollView, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { sceneLocation } from '@promorang/shared';
import { Text, View } from '@/components/Themed';
import { ResponsivePressable as Pressable } from '@/components/ResponsivePressable';
import { BorderRadius, Colors, Spacing } from '@/constants/DesignTokens';
import { useScenes } from '@/hooks/useScenes';

export default function ScenesScreen() {
  const { scenes, loading, error } = useScenes();
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.nav}><Pressable accessibilityLabel="Go back" style={styles.round} onPress={() => router.back()}><Ionicons name="arrow-back" size={20} color={Colors.white}/></Pressable><Text style={styles.navTitle}>SCENES</Text><View style={{flexDirection:'row',gap:8}}><Pressable accessibilityLabel="Explore Map" style={styles.round} onPress={() => router.push('/map' as any)}><Ionicons name="map-outline" size={19} color={Colors.primary}/></Pressable><Pressable accessibilityLabel="Search" style={styles.round} onPress={() => router.push('/search')}><Ionicons name="search" size={19} color={Colors.white}/></Pressable></View></View>
    <Text style={styles.eyebrow}>FIND YOUR PEOPLE</Text><Text style={styles.title}>The world that feels like yours.</Text><Text style={styles.intro}>People, places and rituals worth returning to—not another category to follow.</Text>
    {loading ? <ActivityIndicator style={{marginTop:40}} color={Colors.primary}/> : error ? <Pressable style={styles.empty} onPress={() => router.replace('/scenes')}><Ionicons name="cloud-offline-outline" size={28} color={Colors.primary}/><Text style={styles.emptyTitle}>Scenes could not refresh.</Text><Text style={styles.emptyCopy}>Tap to try again.</Text></Pressable> : scenes.length ? scenes.map(scene => <Pressable key={scene.id} onPress={() => router.push(`/scene/${scene.slug}` as any)} style={styles.card}><ImageBackground source={scene.image_url ? {uri:scene.image_url} : undefined} style={styles.image} imageStyle={styles.imageRadius}><View style={styles.shade}/><View style={styles.cardTop}><Text style={styles.location}>{sceneLocation(scene).toUpperCase()}</Text><Ionicons name="arrow-up" size={20} color={Colors.white} style={{transform:[{rotate:'45deg'}]}}/></View><View style={styles.cardCopy}><Text style={styles.cardTitle}>{scene.title}</Text><Text numberOfLines={2} style={styles.cardDetail}>{scene.metadata.tagline || scene.description}</Text></View></ImageBackground></Pressable>) : <View style={styles.empty}><Ionicons name="heart-outline" size={30} color={Colors.primary}/><Text style={styles.emptyTitle}>The first public Scene is still forming.</Text><Text style={styles.emptyCopy}>Find a gathering worth joining while the people and places around it become a recognizable Scene.</Text><Pressable style={styles.action} onPress={() => router.push('/discover')}><Text style={styles.actionText}>Discover Moments</Text><Ionicons name="arrow-forward" size={17} color={Colors.black}/></Pressable></View>}
    <View style={{height:60}}/>
  </ScrollView></View>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.black},content:{paddingHorizontal:Spacing.container},nav:{paddingTop:54,paddingBottom:30,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},round:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:Colors.gray[900],borderWidth:1,borderColor:Colors.border},navTitle:{color:Colors.gray[400],fontFamily:'SpaceMono',fontSize:12,letterSpacing:1.2},eyebrow:{color:Colors.primary,fontFamily:'SpaceMono',fontSize:12,letterSpacing:1},title:{color:Colors.white,fontSize:40,lineHeight:42,fontWeight:'900',letterSpacing:-1.6,marginTop:8,maxWidth:340},intro:{color:Colors.gray[400],fontSize:14,lineHeight:21,marginTop:12,maxWidth:330,marginBottom:25},card:{height:420,overflow:'hidden',borderRadius:BorderRadius['2xl'],marginBottom:15,borderWidth:1,borderColor:Colors.border},image:{flex:1,padding:18,justifyContent:'space-between',backgroundColor:'#1A120E'},imageRadius:{borderRadius:BorderRadius['2xl']},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.38)'},cardTop:{flexDirection:'row',justifyContent:'space-between',backgroundColor:'transparent'},location:{color:Colors.accent,fontFamily:'SpaceMono',fontSize:12,letterSpacing:.8},cardCopy:{backgroundColor:'transparent'},cardTitle:{color:Colors.white,fontSize:34,lineHeight:36,fontWeight:'900',letterSpacing:-1.1},cardDetail:{color:Colors.gray[200],fontSize:13,lineHeight:18,marginTop:7},empty:{marginTop:20,paddingVertical:45,paddingHorizontal:20,borderTopWidth:1,borderBottomWidth:1,borderColor:Colors.border,alignItems:'flex-start'},emptyTitle:{color:Colors.white,fontSize:25,lineHeight:29,fontWeight:'900',marginTop:16},emptyCopy:{color:Colors.gray[400],fontSize:13,lineHeight:19,marginTop:8},action:{marginTop:22,minHeight:48,paddingHorizontal:18,borderRadius:16,backgroundColor:Colors.primary,flexDirection:'row',alignItems:'center',gap:8},actionText:{color:Colors.black,fontSize:13,fontWeight:'900'}});
