import { useState } from "react";
import { AlertTriangle, BadgeCheck, Building2, CheckCircle2, CircleDollarSign, ClipboardCheck, FileCheck2, MapPinCheck, Megaphone, QrCode, ScanLine, Sparkles, Store, Users2, WandSparkles } from "lucide-react";

type Role = "Creator"|"Host"|"Merchant"|"Brand"|"Agency"|"Admin";

const roles: Role[] = ["Creator","Host","Merchant","Brand","Agency","Admin"];

const roleCopy: Record<Role,{job:string,outcome:string,current:string,proof:string,decision:string}> = {
  Creator:{job:"Choose worthwhile work, complete it, prove it, get approved and build reputation.",outcome:"Useful distribution and attributable action.",current:"Complete the accepted brief and submit proof.",proof:"Approved deliverable + attributable action.",decision:"Earn, improve reputation, unlock better work."},
  Host:{job:"Fill it, run it and prove who came.",outcome:"Attendance and useful participation.",current:"Prepare arrivals and remove blockers before doors open.",proof:"Verified check-ins + participation records.",decision:"Retarget the audience, repeat or improve the Moment."},
  Merchant:{job:"Turn attention into visits, redemptions, purchases and returns.",outcome:"Verified customer action at a real place.",current:"Serve the live offer and validate each use correctly.",proof:"Redemption, transaction or visit evidence.",decision:"Replenish, change, repeat or retarget."},
  Brand:{job:"Create measurable customer movement and know what actually happened.",outcome:"Attributable trial, visit, purchase, review, referral or repeat.",current:"Get the activation ready to launch with a clear proof contract.",proof:"Verified action evidence with attribution confidence.",decision:"Repeat, change, stop or scale."},
  Agency:{job:"Produce an undeniable client result and package the proof.",outcome:"Measured client movement tied to the correct client workspace.",current:"Move the next client activation from blocked to ready.",proof:"Client-attributed proof + evidence pack.",decision:"Package the result and expand the account."},
  Admin:{job:"Find the highest-priority exception and resolve it with an audit trail.",outcome:"Healthy trustworthy platform operation.",current:"Resolve the highest-impact exception first.",proof:"Resolution record + audit event.",decision:"Restore operation, escalate or change controls."},
};

function JobRail({role}:{role:Role}) { const r=roleCopy[role]; return <div className="rounded-[1.5rem] border border-white/10 bg-[#0d0d0f] p-6"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ff6a00]">{role} job contract</p><h3 className="mt-3 font-serif text-3xl font-bold">{r.job}</h3><div className="mt-7 space-y-4 text-sm">{[["OUTCOME",r.outcome],["CURRENT MOVE",r.current],["PROOF",r.proof],["NEXT DECISION",r.decision]].map(([a,b])=><div key={a} className="grid gap-1 border-b border-white/8 pb-4 md:grid-cols-[130px_1fr]"><span className="text-[9px] font-black tracking-[.15em] text-white/28">{a}</span><span>{b}</span></div>)}</div></div> }

function CreatorArtifact(){ const [submitted,setSubmitted]=useState(false); return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="overflow-hidden rounded-[1.5rem] border border-[#b58cff]/30 bg-[#17111f]"><div className="border-b border-[#b58cff]/20 p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#b58cff]">CREATOR BRIEF · CB-0421</p><h3 className="mt-3 font-serif text-4xl font-bold">Drive verified test-drive interest.</h3></div><WandSparkles className="text-[#b58cff]"/></div><p className="mt-3 text-sm text-white/45">Flash Motors · Move Jamaica · due Friday 4 PM</p></div><div className="p-6"><div className="grid gap-4 sm:grid-cols-2">{[["DELIVERABLE","1 vertical video + tracked link"],["AUDIENCE","Kingston auto / lifestyle"],["PROOF","Approved post + attributable booking"],["REWARD","40 Gems + reputation credit"]].map(([a,b])=><div key={a} className="border border-white/10 p-4"><p className="text-[9px] font-black tracking-[.15em] text-[#ff9a4d]">{a}</p><p className="mt-2 font-bold">{b}</p></div>)}</div><button onClick={()=>setSubmitted(true)} className="mt-6 w-full rounded-full bg-[#eadcc6] py-3 text-sm font-black text-black">{submitted?"Proof submitted · awaiting review":"Submit proof package"}</button></div></div><div className="rounded-[1.5rem] border border-white/10 p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#b58cff]">PROOF SUBMISSION · PS-0421</p><div className="mt-6 space-y-4">{[["Deliverable","Video uploaded"],["Tracked action","3 test-drive bookings"],["Approval",submitted?"Pending review":"Not submitted"],["Settlement",submitted?"Held until approval":"Not started"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-white/8 pb-4 text-sm"><span className="text-white/35">{a}</span><b>{b}</b></div>)}</div></div></div>; }

function HostArtifact(){ return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-[1.5rem] border border-[#f6c453]/25 bg-[#130f07] p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#f6c453]">RUN OF SHOW · MOMENT M-0918</p><h3 className="mt-3 font-serif text-4xl font-bold">AFTRHRS · Sea Deck</h3><div className="mt-7 space-y-3">{[["8:00 PM","Doors prep","Ready"],["9:30 PM","RSVP arrival window","42 expected"],["10:00 PM","Moment live","—"],["11:30 PM","RSVP cutoff","Verify late arrivals"],["1:30 AM","Proof close","Reconcile check-ins"]].map(([t,a,s])=><div key={t} className="grid grid-cols-[90px_1fr_auto] gap-4 border-b border-white/8 pb-3 text-sm"><b>{t}</b><span>{a}</span><span className="text-[#f6c453]">{s}</span></div>)}</div></div><div className="rounded-[1.5rem] border border-[#22c55e]/20 bg-[#07120b] p-6"><div className="flex items-center gap-2 text-[#22c55e]"><ScanLine className="h-5 w-5"/><p className="text-[10px] font-black tracking-[.18em]">ARRIVAL LEDGER</p></div><div className="mt-6 grid grid-cols-3 gap-3">{[["RSVP","42"],["VERIFIED","28"],["WALK-IN","7"]].map(([a,b])=><div key={a} className="border border-white/10 p-4"><p className="text-[9px] text-white/30">{a}</p><p className="mt-2 text-2xl font-bold">{b}</p></div>)}</div><p className="mt-5 text-xs leading-5 text-white/45">RSVP is intent. Only verified arrival counts as attendance proof.</p></div></div>; }

function MerchantArtifact(){ const [validated,setValidated]=useState(false); return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-[1.5rem] border border-[#ff6a00]/25 bg-[#120b08] p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#ff9a4d]">LIVE OFFER · OF-2031</p><h3 className="mt-3 font-serif text-4xl font-bold">20% off chef's lunch menu</h3></div><Store className="text-[#ff6a00]"/></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{[["PLACE","Broken Plate · Liguanea"],["WINDOW","12–3 PM"],["PROOF TYPE","Merchant-validated redemption"],["AVAILABLE","18 uses remaining"]].map(([a,b])=><div key={a} className="border border-white/10 p-4"><p className="text-[9px] text-white/28">{a}</p><p className="mt-2 font-bold">{b}</p></div>)}</div></div><div className="rounded-[1.5rem] border border-white/10 p-6"><div className="flex items-center gap-2"><QrCode className="text-[#22c55e]"/><p className="text-[10px] font-black tracking-[.18em] text-[#22c55e]">VALIDATION SLIP · VL-1182</p></div><p className="mt-5 font-serif text-3xl font-bold">{validated?"Use verified":"Ready to verify"}</p><div className="mt-5 space-y-3 text-sm">{[["PromoCard","PC-004218"],["Offer","OF-2031"],["Place","Broken Plate"],["Status",validated?"Verified · 1:14 PM":"Awaiting scan"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-white/8 pb-3"><span className="text-white/35">{a}</span><b>{b}</b></div>)}</div><button onClick={()=>setValidated(true)} className="mt-6 w-full rounded-full bg-[#22c55e] py-3 text-sm font-black text-black">{validated?"Validation recorded":"Validate use"}</button></div></div>; }

function BrandArtifact(){ return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-[1.5rem] border border-[#4cc6f0]/22 bg-[#071319] p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#4cc6f0]">ACTIVATION SHEET · AC-5021</p><h3 className="mt-3 font-serif text-4xl font-bold">First 50 for Flash Motors</h3></div><Megaphone className="text-[#4cc6f0]"/></div><div className="mt-7 space-y-4">{[["OUTCOME","50 attributable test-drive actions"],["AUDIENCE","Kingston auto-curious adults"],["ACTION","Book and attend a test drive"],["PROOF","Booking + merchant/venue validation"],["VALUE","Priority slot + creator distribution"]].map(([a,b])=><div key={a} className="grid grid-cols-[110px_1fr] border-b border-white/8 pb-4 text-sm"><b className="text-[9px] tracking-[.15em] text-white/28">{a}</b><span>{b}</span></div>)}</div></div><div className="rounded-[1.5rem] border border-white/10 p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#f6c453]">EVIDENCE PACK · EP-5021</p><div className="mt-6 grid gap-3">{[["Bookings","18 verified intent records"],["Attendance","11 verified test drives"],["Creator proof","4 approved deliverables"],["Attribution","Direct link + validation"],["Decision","Increase creator coverage"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-white/8 pb-3 text-sm"><span className="text-white/35">{a}</span><b>{b}</b></div>)}</div></div></div>; }

function AgencyArtifact(){ return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-[1.5rem] border border-[#b58cff]/22 bg-[#15101c] p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#b58cff]">CLIENT LEDGER · PANDXTRA</p><h3 className="mt-3 font-serif text-4xl font-bold">Managed work, without losing client truth.</h3><div className="mt-7 space-y-3">{[["Manchester Hills Foods","Brand","Proof ready","37 verified redemptions"],["Flash Motors","Brand","Live","11 verified test drives"],["Sea Deck","Venue","Preparing","Missing offer inventory"]].map(([n,t,s,p])=><div key={n} className="grid grid-cols-[1fr_90px_90px_1fr] gap-3 border-b border-white/8 pb-4 text-sm"><b>{n}</b><span className="text-white/35">{t}</span><span className="text-[#b58cff]">{s}</span><span>{p}</span></div>)}</div></div><div className="rounded-[1.5rem] border border-white/10 p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#f6c453]">MANAGED RESULT PACK · MR-117</p><p className="mt-4 text-xs text-white/35">Manchester Hills Foods · managed by Pandxtra</p><h4 className="mt-3 font-serif text-3xl font-bold">37 verified offer redemptions.</h4><p className="mt-3 text-sm leading-6 text-white/48">Client attribution remains Manchester Hills Foods. Agency context remains visible throughout the workspace.</p><div className="mt-6 border-t border-white/10 pt-5 text-sm"><p>Decision <b className="float-right">Repeat with larger audience</b></p></div></div></div>; }

function AdminArtifact(){ const [resolved,setResolved]=useState(false); return <div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="rounded-[1.5rem] border border-[#ff6a00]/30 bg-[#120b08] p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#ff9a4d]">EXCEPTION CASE · EX-7712</p><h3 className="mt-3 font-serif text-4xl font-bold">Proof conflict needs review.</h3></div><AlertTriangle className="text-[#ff6a00]"/></div><div className="mt-7 space-y-4">{[["SEVERITY","High"],["OBJECT","Merchant validation VL-1182"],["CONFLICT","Duplicate validation timestamp"],["IMPACT","1 reward settlement held"],["OWNER","Admin · Operations"]].map(([a,b])=><div key={a} className="grid grid-cols-[110px_1fr] border-b border-white/8 pb-4 text-sm"><b className="text-[9px] tracking-[.15em] text-white/28">{a}</b><span>{b}</span></div>)}</div><button onClick={()=>setResolved(true)} className="mt-6 rounded-full bg-[#eadcc6] px-5 py-3 text-sm font-black text-black">{resolved?"Resolved":"Resolve exception"}</button></div><div className="rounded-[1.5rem] border border-white/10 p-6"><div className="flex items-center gap-2"><FileCheck2 className="text-[#22c55e]"/><p className="text-[10px] font-black tracking-[.18em] text-[#22c55e]">RESOLUTION RECORD · RR-7712</p></div><div className="mt-6 space-y-4 text-sm">{[["Decision",resolved?"Duplicate rejected":"Pending"],["Evidence",resolved?"Original merchant scan retained":"Awaiting review"],["Settlement",resolved?"Released":"Held"],["Audit",resolved?"Recorded 9:41 AM":"Not written"]].map(([a,b])=><div key={a} className="flex justify-between border-b border-white/8 pb-4"><span className="text-white/35">{a}</span><b>{b}</b></div>)}</div></div></div>; }

function RoleArtifact({role}:{role:Role}) { switch(role){case "Creator": return <CreatorArtifact/>; case "Host": return <HostArtifact/>; case "Merchant": return <MerchantArtifact/>; case "Brand": return <BrandArtifact/>; case "Agency": return <AgencyArtifact/>; case "Admin": return <AdminArtifact/>;} }

export function StakeholderExperienceLab(){ const [role,setRole]=useState<Role>("Creator"); return <div className="border-t border-white/10 pt-20"><div className="mb-12 grid gap-6 lg:grid-cols-[1fr_.5fr] lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#ff6a00]">PROMORANG stakeholder system · supply-side design</p><h2 className="mt-4 max-w-5xl font-serif text-5xl font-bold leading-[.9] tracking-[-.055em] md:text-7xl">Every stakeholder needs an object language for their job.</h2></div><p className="border-l border-[#ff6a00]/35 pl-5 text-sm leading-6 text-white/48">The participant owns access, proof and kept value. Supply-side roles need equally concrete work objects: briefs, run sheets, activation sheets, validation slips, evidence packs, client ledgers and exception records.</p></div><div className="mb-7 flex flex-wrap gap-2">{roles.map(r=><button key={r} onClick={()=>setRole(r)} className={`rounded-full border px-5 py-2 text-xs font-bold ${role===r?"border-[#ff6a00]/60 bg-[#ff6a00]/10 text-white":"border-white/10 text-white/45"}`}>{r}</button>)}</div><div className="grid gap-6 xl:grid-cols-[.42fr_1.58fr]"><JobRail role={role}/><RoleArtifact role={role}/></div></div>; }
