
-- Insert clearly labeled demo content pieces
INSERT INTO content_pieces (creator_id, platform, platform_url, title, description, media_url, total_shares, available_shares, share_price, current_revenue, creator_username, engagement_shares_total, engagement_shares_remaining) VALUES
(2, 'TikTok', 'https://tiktok.com/@democreator/viral-dance', '[Demo] Viral Dance Challenge Tutorial', '[Demo] Learn the hottest dance moves with this step-by-step tutorial! Perfect for beginners and pros alike. Demo content for testing - no real earnings.', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', 1000, 650, 2.45, 1250.80, 'sarahcreates', 200, 145),
(3, 'Instagram', 'https://instagram.com/p/demo-morning-routine', '[Demo] Morning Routine for Productivity', '[Demo] My 5-step morning routine that changed everything! Start your day right with these simple habits. Demo content - no real value transfers.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop', 500, 280, 3.20, 890.45, 'mikeviral', 100, 75),
(4, 'YouTube', 'https://youtube.com/watch?v=demo-fitness', '[Demo] 10-Minute Home Workout', '[Demo] Get fit at home with this quick and effective workout routine! No equipment needed. Demo fitness content for platform testing.', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop', 800, 480, 1.95, 1560.30, 'emmafitness', 150, 95),
(9, 'Twitch', 'https://twitch.tv/demogamer/epic-stream', '[Demo] Epic Gaming Stream Highlights', '[Demo] Watch the best moments from last nights stream! Incredible plays and funny fails. Demo stream content for testing.', 'https://images.unsplash.com/photo-1556438064-2d7646166914?w=400&h=300&fit=crop', 1200, 720, 2.80, 2016.75, 'gamerpro', 200, 150),
(8, 'Instagram', 'https://instagram.com/p/demo-fashion-haul', '[Demo] Spring Fashion Haul & Styling', '[Demo] Trying on the latest spring fashion trends! Affordable finds and styling tips. Demo fashion content - no real brand partnerships.', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=400&fit=crop', 1500, 900, 2.15, 1935.60, 'fashionista', 250, 180);

-- Insert clearly labeled demo drops (various types)
INSERT INTO drops (creator_id, title, description, drop_type, difficulty, key_cost, gem_reward_base, gem_pool_total, gem_pool_remaining, follower_threshold, time_commitment, requirements, deliverables, max_participants, current_participants, status, is_proof_drop, is_paid_drop, move_cost_points, key_reward_amount) VALUES
(2, '[Demo] Create TikTok Dance Tutorial', '[Demo] We need creators to make engaging dance tutorials! Show off your moves and teach others. This is demo content - no real gems awarded despite interface suggestions.', 'ugc_creation', 'easy', 0, 0, 0, 0, 1000, '2-3 hours', 'Basic dance skills, good lighting, energetic personality', 'One 60-90 second TikTok video with clear tutorial steps', 50, 12, 'active', true, false, 0, 0),
(3, '[Demo] Product Review Challenge', '[Demo] Create authentic reviews for our latest product line! Share your honest experience. Demo drop for testing purposes - no real rewards.', 'reviews', 'medium', 3, 125, 5000, 4200, 500, '3-4 hours', 'Previous review experience, good camera/audio quality', 'Detailed review video (3-5 minutes) and written summary', 25, 8, 'active', false, true, 0, 0),
(4, '[Demo] Fitness Content Creation', '[Demo] Show off your workout routines in creative content! Perfect for fitness enthusiasts. Demo content only - no real currency exchanges.', 'content_clipping', 'medium', 2, 80, 3000, 2400, 1000, '4-5 hours', 'Fitness experience, good video quality, motivational personality', 'Workout routine video (3-5 minutes) with clear instructions', 30, 15, 'active', false, true, 0, 0),
(8, '[Demo] Social Media Engagement Move', '[Demo] Like and share our content across platforms for keys! Demo move action - no real currency exchange despite interface display.', 'challenges_events', 'easy', 0, 0, 0, 0, 0, '5 minutes', 'Active social media accounts', 'Like, comment, and share specified posts', 100, 45, 'active', false, false, 5, 2),
(9, '[Demo] Gaming Community Survey', '[Demo] Help us understand gaming community needs with this quick survey. Demo proof drop for testing master key activation system.', 'surveys', 'easy', 0, 0, 0, 0, 0, '10 minutes', 'Gaming experience, honest feedback', 'Complete 20-question survey about gaming preferences', 200, 67, 'active', true, false, 0, 0);

-- Insert clearly labeled demo tasks
INSERT INTO tasks (creator_id, title, description, category, difficulty, reward_amount, currency_type, follower_threshold, time_commitment, requirements, deliverables, max_participants, current_participants, status) VALUES
(2, '[Demo] Design Instagram Story Templates', '[Demo] Create 5 modern Instagram story templates for lifestyle brands. Demo task - no real payment processing despite interface display.', 'Design', 'medium', 150, 'USD', 0, '3-4 hours', 'Graphic design experience, knowledge of Instagram dimensions', '5 unique story templates in PNG format', 3, 1, 'active'),
(9, '[Demo] Gaming Thumbnail Creation', '[Demo] Design eye-catching YouTube thumbnails for gaming content. Demo task for testing purposes - no real payments.', 'Design', 'easy', 85, 'USD', 0, '2-3 hours', 'Photoshop/design skills, understanding of YouTube best practices', '10 thumbnail designs with source files', 5, 2, 'active'),
(8, '[Demo] Social Media Content Writing', '[Demo] Write engaging captions for Instagram and TikTok posts. Demo content creation task - testing interface only.', 'Content Creation', 'easy', 75, 'USD', 500, '2 hours', 'Strong writing skills, social media experience', '20 captions with hashtag recommendations', 8, 3, 'active');

-- Insert clearly labeled demo social forecasts
INSERT INTO social_forecasts (creator_id, platform, content_url, content_id, forecast_type, target_value, current_value, odds, pool_size, creator_initial_amount, creator_side, expires_at, status) VALUES
(2, 'TikTok', 'https://tiktok.com/@democreator/demo-forecast-1', (SELECT id FROM content_pieces WHERE title = '[Demo] Viral Dance Challenge Tutorial'), 'likes', 50000, 12500, 2.5, 1250.75, 100, 'over', datetime('now', '+7 days'), 'active'),
(9, 'YouTube', 'https://youtube.com/watch?v=demo-forecast-gaming', NULL, 'views', 100000, 35000, 1.8, 2100.50, 200, 'over', datetime('now', '+14 days'), 'active'),
(8, 'Instagram', 'https://instagram.com/p/demo-forecast-fashion', (SELECT id FROM content_pieces WHERE title = '[Demo] Spring Fashion Haul & Styling'), 'likes', 25000, 8900, 3.2, 950.25, 150, 'under', datetime('now', '+10 days'), 'active');
