import type { CommunityAction, CommunityWorkspaceData } from '@/types/community';
import { ActionButton, dateLabel, Empty, human, SectionHeading } from './CommunitySections';
import { Field, inputClass, goalForm, moveForm, postForm, roleField, secondaryClass, tierField, type CommunityForm } from './CommunityForms';

export function CommunityLead({ data, onAction, onForm }: { data: CommunityWorkspaceData; onAction: CommunityAction; onForm: (f: CommunityForm) => void }) {
  if (!data.lead) return <Empty>This area is available to community leads.</Empty>;
  const people = new Map(data.lead.members.map(m => [m.user_id, m.display_name]));
  const waiting = data.moves.filter(m => m.status === 'proposed');
  function sessionForm(): CommunityForm {
    return { action: 'session', title: 'Put a session on the calendar', description: 'Set a real date, an access link, and who the session serves. Times entered here use your local timezone.',
      fields: <>
        <Field label="Session name"><input name="title" required minLength={5} maxLength={140} className={inputClass} /></Field>
        <Field label="What will members get from it?"><textarea name="description" required minLength={10} maxLength={2000} className={inputClass} rows={3} /></Field>
        <Field label="Starts in your local time"><input type="datetime-local" name="starts_at" required className={inputClass} /></Field>
        <Field label="Minutes"><input type="number" name="duration_minutes" defaultValue={60} min={15} max={480} required className={inputClass} /></Field>
        <Field label="Join link"><input name="join_url" className={inputClass} placeholder="https://…" /></Field>
        <Field label="Recording link · optional"><input name="replay_url" className={inputClass} /></Field>
        <Field label="Existing Moment ID · optional"><input name="moment_id" className={inputClass} placeholder="Link an existing Promorang Moment" /></Field>
        {tierField()}{roleField(data)}
      </>, transform: v => ({ ...v, duration_minutes: Number(v.duration_minutes), starts_at: new Date(String(v.starts_at)).toISOString(),
        join_url: v.join_url || null, replay_url: v.replay_url || null, moment_id: v.moment_id || null, required_role: v.required_role || null }) };
  }
  return <><SectionHeading kicker="Run the community" title="Make room for good work." />
    <div className="mb-10 flex flex-wrap gap-3"><button className={secondaryClass} onClick={() => onForm(goalForm())}>Set a goal</button><button className={secondaryClass} onClick={() => onForm(moveForm(data))}>Write a brief</button><button className={secondaryClass} onClick={() => onForm(sessionForm())}>Schedule a session</button><button className={secondaryClass} onClick={() => onForm(postForm(data))}>Share a resource</button></div>
    <section className="mb-12"><SectionHeading kicker={`${data.lead.reviewQueue.length} waiting`} title="Give the work a fair review." />
      <div className="space-y-6">{data.lead.reviewQueue.map(s => <article key={s.id} className="rounded-2xl border border-white/20 p-5"><p className="text-xs text-orange-200">{people.get(s.user_id) || 'Community member'} · submitted {dateLabel(s.submitted_at, true)}</p><h3 className="mt-2 text-xl font-semibold">{s.move.title}</h3><p className="mt-3 text-sm text-white/65">The brief asks for: {s.move.proof_prompt}</p><p className="mt-4 whitespace-pre-line text-sm leading-7">{s.proof}</p>{s.proof_url && <a href={s.proof_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex min-h-11 items-center text-sm text-orange-200">Open proof →</a>}
        <p className="my-4 text-xs text-white/65">Deadline {dateLabel(s.move.due_at, true)} · Approval awards {s.move.points} points and {s.move.gems} Gems.</p>
        {s.user_id === data.membership.user_id ? <p className="text-sm text-orange-200">Another lead must review your work.</p> : <button className={secondaryClass} onClick={() => onForm({ action: 'review', title: 'Review this contribution', description: 'Check the evidence against the brief. Record only the measurable result you can verify; points and job payment follow the approved brief.', values: { move_id: s.move_id, submission_id: s.id },
          fields: <><Field label="Outcome"><select name="decision" className={inputClass} defaultValue="changes_requested"><option value="changes_requested">Ask for changes</option><option value="approved">Approve and release rewards</option><option value="declined">Decline this submission</option></select></Field>
            <Field label="Verified progress toward the linked win"><input name="verified_value" type="number" min={0} max={100000000} defaultValue={0} required className={inputClass} /></Field><Field label="Give a useful review note"><textarea name="feedback" required minLength={10} maxLength={3000} rows={3} className={inputClass} /></Field></>, transform: v => ({ ...v, verified_value: Number(v.verified_value) }), submit: 'Record review' })}>Review the proof</button>}
      </article>)}{!data.lead.reviewQueue.length && <Empty>No work waiting for review.</Empty>}</div>
    </section>
    <section className="mb-12"><SectionHeading kicker="Pitches" title="Open the next useful move." /><div className="divide-y divide-white/15">{waiting.map(m => <article key={m.id} className="py-5"><h3 className="text-lg font-semibold">{m.title}</h3><p className="mt-2 text-sm leading-6 text-white/70">{m.brief}</p><p className="mt-3 text-sm text-orange-200">{m.capacity} places × {Number(m.gems)} Gems = {Number(m.gems) * m.capacity} Gems to set aside</p><p className="mt-2 text-xs leading-6 text-white/60">{m.points} points per approval · {m.proof_prompt}</p><div className="mt-4 flex flex-wrap gap-3">
      <button className={secondaryClass} onClick={() => onForm({ action: 'publish', title: 'Open this move', description: `This opens ${m.capacity} places. ${Number(m.gems) > 0 ? `${Number(m.gems) * m.capacity} Gems will be taken from your available Gem balance and set aside for this job.` : 'This brief rewards points only.'} The terms cannot change after opening.`, values: { move_id: m.id }, fields: <p className="text-sm leading-7">{m.title}<br />Due {dateLabel(m.due_at, true)} · Jamaica<br />{m.proof_prompt}</p>, submit: 'Set aside funding and open' })}>Review and open</button>
      <ActionButton secondary action="close" values={{ move_id: m.id }} onAction={onAction}>Close pitch</ActionButton></div></article>)}{!waiting.length && <Empty>No pitches waiting. Start with a goal and a brief that moves it forward.</Empty>}</div></section>
    <section className="mb-12"><SectionHeading kicker="Membership" title="Welcome the right people." /><div className="divide-y divide-white/15">{data.lead.members.map(m => <article key={m.id} className="flex flex-wrap justify-between gap-4 py-5"><div><h3 className="font-semibold">{m.display_name} <span className="ml-2 text-xs font-normal capitalize text-orange-200">{m.status} · {m.tier}{m.can_manage ? ' · lead' : ''}</span></h3><p className="mt-1 text-xs text-white/60">{m.career_path}</p><p className="mt-2 text-sm leading-6 text-white/70">{m.personal_goal}</p></div>{!m.can_manage && <button className={secondaryClass} onClick={() => onForm({ action: 'membership', title: `Membership for ${m.display_name}`, description: 'Approve membership separately from platform subscriptions. Pausing or removing membership closes access to private community work.', values: { id: m.id }, fields: <><Field label="Status"><select name="status" defaultValue={m.status === 'pending' ? 'active' : m.status} className={inputClass}><option value="active">Active member</option><option value="paused">Paused</option><option value="removed">Removed</option></select></Field><Field label="Community tier"><select name="tier" defaultValue={m.tier} className={inputClass}><option value="free">Free</option><option value="premium">Premium</option><option value="super">Super</option></select></Field></> })}>Review membership</button>}</article>)}</div></section>
    <section className="mb-12"><SectionHeading kicker="Roles and check-ins" title="Help people keep their place." /><div className="divide-y divide-white/15">{data.lead.applications.map(s => <article key={s.id} className="py-5"><h3 className="font-semibold">{people.get(s.user_id)} · {data.framework.roles.find(r => r.id === s.role_slug)?.name}</h3><p className="mt-2 text-xs text-orange-200">{human(s.status)} · Check-in {dateLabel(s.review_at)}</p><p className="mt-3 text-sm leading-6 text-white/70">{s.application}</p>{s.user_id !== data.membership.user_id && <button className={`${secondaryClass} mt-4`} onClick={() => onForm({ action: s.status === 'applied' ? 'appoint' : 'review_role', title: s.status === 'applied' ? 'Review this role application' : 'Give this role a check-in', description: s.status === 'applied' ? 'A new appointment starts a 90-day term with a supported first month.' : 'The system checks accepted points and role work. Meeting the rule keeps access active. Otherwise the grace period begins; expired terms need a new application.', values: { id: s.id }, fields: <>{s.status === 'applied' && <Field label="Decision"><select name="approved" className={inputClass}><option value="true">Appoint</option><option value="false">Decline for now</option></select></Field>}<Field label="Feedback and next step"><textarea name="note" required minLength={10} maxLength={2000} className={inputClass} rows={3} /></Field></>, transform: v => ({ note: v.note, ...(s.status === 'applied' ? { approved: v.approved === 'true' } : {}) }) })}>{s.status === 'applied' ? 'Review application' : 'Run check-in'}</button>}</article>)}{!data.lead.applications.length && <Empty>Role applications appear here when a member puts their name forward.</Empty>}</div></section>
    <details className="mb-8 border-y border-white/20 py-5"><summary className="cursor-pointer font-semibold">Role requirements</summary><p className="mt-3 text-sm text-white/60">Starter requirements are 60 points and two accepted moves in the role’s contribution type per 30 days. Share any policy change with the community before the next review.</p>{data.definitions.map(d => <div key={d.slug} className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="text-sm">{d.name} · {d.min_points} points · {d.min_moves} moves</span><button className={secondaryClass} onClick={() => onForm({ action: 'policy', title: `Requirements for ${d.name}`, description: 'Updated requirements will be visible to members and used in subsequent check-ins.', values: { role_slug: d.slug }, fields: <><Field label="Contribution points per review"><input name="min_points" type="number" defaultValue={d.min_points} min={0} max={10000} required className={inputClass} /></Field><Field label="Accepted moves in this role"><input name="min_moves" type="number" defaultValue={d.min_moves} min={1} max={100} required className={inputClass} /></Field></>, transform: v => ({ min_points: Number(v.min_points), min_moves: Number(v.min_moves) }) })}>Adjust</button></div>)}</details>
    <details className="mb-8 border-b border-white/20 pb-5"><summary className="cursor-pointer font-semibold">Ongoing community commitments</summary><div className="mt-5 space-y-5">{data.framework.ongoing.map(o => <div key={o.title}><h3 className="text-sm font-semibold">{o.title}</h3><p className="mt-1 text-sm leading-6 text-white/65">{o.purpose}</p></div>)}</div></details>
    <details className="mb-8 border-b border-white/20 pb-5"><summary className="cursor-pointer font-semibold">Close finished work and return unused funding</summary><div className="mt-4 space-y-5">{data.moves.filter(m => m.status === 'open').map(m => <div key={m.id} className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{m.title}</p><p className="mt-1 text-xs text-white/60">{Number(m.secured_gems) - Number(m.released_gems) - Number(m.refunded_gems)} Gems remain set aside</p></div><ActionButton secondary action="close" values={{ move_id: m.id }} onAction={onAction}>Close and return unused Gems</ActionButton></div>)}</div></details>
    <details className="mb-8 border-b border-white/20 pb-5"><summary className="cursor-pointer font-semibold">Unfinished work past its deadline</summary><p className="mt-3 text-sm leading-6 text-white/65">Speak with the member before releasing an unfinished claim. Submitted proof must receive a review. Releasing a claim does not remove approved earnings.</p>{data.lead.unfinished.filter(s => Date.parse(s.move.due_at) <= Date.now()).map(s => <div className="mt-5" key={s.id}><p className="mb-3 text-sm">{people.get(s.user_id)} · {s.move.title}</p><button className={secondaryClass} onClick={() => onForm({ action: 'release_claim', title: 'Release this unfinished place', description: 'The deadline has passed. Explain the decision so the member has a clear record.', values: { move_id: s.move_id, submission_id: s.id }, fields: <Field label="Reason and next step"><textarea name="feedback" minLength={10} maxLength={2000} required rows={3} className={inputClass} /></Field>, submit: 'Release the place' })}>Review unfinished claim</button></div>)}</details>
    {data.lead.canAssignLeads && <details className="mb-8 border-b border-white/20 pb-5"><summary className="cursor-pointer font-semibold">Assign community leads</summary><p className="mt-3 text-sm leading-6 text-white/65">Leads approve members, review work, and fund jobs from their own available Gems. Two leads allow independent review of each other’s work. This does not grant platform administrator access.</p>{data.lead.members.filter(m => m.status === 'active' && m.user_id !== data.membership.user_id).map(m => <div className="mt-4 flex flex-wrap items-center justify-between gap-3" key={m.id}><span className="text-sm">{m.display_name}</span><ActionButton secondary action="lead_access" values={{ id: m.id, can_manage: !m.can_manage }} onAction={onAction}>{m.can_manage ? 'Remove lead access' : 'Make community lead'}</ActionButton></div>)}</details>}
    <details><summary className="cursor-pointer font-semibold">Recent operations</summary><div className="mt-4 divide-y divide-white/10">{data.lead.audit.map(a => <p key={a.id} className="py-3 text-xs text-white/65">{people.get(a.actor_id) || 'Member'} · {human(a.action)} · {dateLabel(a.created_at, true)}</p>)}</div></details>
  </>;
}
