import { Pressable, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert } from 'react-native';
import { Text, View } from '@/components/Themed';
import { BorderRadius, Colors } from '@/constants/DesignTokens';
import { operationalSupabase as db } from '@/lib/operationalSupabase';

type Tier = { id: string; name: string; description: string | null; access_type: string; price: number; currency: string; reward_summary: string | null; status: string };
type Pass = { id: string; tier_id: string; pass_code: string };
type Wallet = { gems: number };

function requestKey(prefix: string) {
  return `${prefix}:${Date.now()}:${Math.random().toString(36).slice(2)}`;
}

export function MomentAccess({ momentId }: { momentId: string }) {
  const queryClient = useQueryClient();
  const { data = { tiers: [], passes: [], wallet: null } } = useQuery({ queryKey: ['moment-access', momentId], queryFn: async () => { const user = (await db.auth.getUser()).data.user; const [tiers, passes, wallet] = await Promise.all([db.from('activation_access_tiers').select('*').eq('moment_id', momentId).in('status', ['open', 'sold_out', 'closed']).order('created_at'), db.from('activation_access_passes').select('*').eq('moment_id', momentId).order('issued_at', { ascending: false }), user ? db.from('economy_wallets').select('gems').eq('user_id', user.id).maybeSingle() : Promise.resolve({ data: null, error: null })]); if (tiers.error) throw tiers.error; if (passes.error) throw passes.error; if (wallet.error) throw wallet.error; return { tiers: (tiers.data || []) as Tier[], passes: (passes.data || []) as Pass[], wallet: wallet.data as Wallet | null }; } });
  const claim = useMutation({ mutationFn: async (tierId: string) => { const { error } = await db.rpc('claim_free_activation_access', { p_tier_id: tierId }); if (error) throw error; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['moment-access', momentId] }); Alert.alert('Your access is ready'); }, onError: (error: Error) => Alert.alert('Access unavailable', error.message) });
  const purchase = useMutation({ mutationFn: async (tierId: string) => { const { error } = await db.rpc('purchase_activation_access_with_gems', { p_tier_id: tierId, p_idempotency_key: requestKey('moment-access') }); if (error) throw error; }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['moment-access', momentId] }); Alert.alert('Your Gems secured this access'); }, onError: (error: Error) => Alert.alert('Access unavailable', error.message) });
  if (!data.tiers.length) return null;
  return <View style={styles.wrap}><View style={styles.heading}><View style={styles.icon}><Ionicons name="ticket" size={19} color={Colors.primary} /></View><View style={styles.flex}><Text style={styles.eyebrow}>CHOOSE YOUR WAY IN</Text><Text style={styles.title}>Access for this Moment</Text><Text style={styles.note}>{Number(data.wallet?.gems || 0).toLocaleString()} Gems available</Text></View></View>{data.tiers.map((tier) => { const pass = data.passes.find((item) => item.tier_id === tier.id); const canBuy = Number(data.wallet?.gems || 0) >= Number(tier.price || 0); return <View key={tier.id} style={styles.card}><View style={styles.row}><View style={styles.flex}><Text style={styles.type}>{tier.access_type.toUpperCase()}</Text><Text style={styles.name}>{tier.name}</Text></View><Text style={styles.price}>{tier.price ? `${tier.price} Gems` : 'Free'}</Text></View><Text style={styles.description}>{tier.description}</Text>{tier.price > 0 && <Text style={styles.note}>US${tier.price} platform value</Text>}{tier.reward_summary && <Text style={styles.reward}>CAN OPEN: {tier.reward_summary}</Text>}{pass ? <View style={styles.pass}><Text style={styles.passLabel}>YOUR ACCESS</Text><Text style={styles.code}>{pass.pass_code}</Text></View> : tier.access_type === 'free' && tier.status === 'open' ? <Pressable disabled={claim.isPending} onPress={() => claim.mutate(tier.id)} style={styles.button}><Text style={styles.buttonText}>Claim access</Text><Ionicons name="arrow-forward" size={16} color={Colors.black} /></Pressable> : tier.access_type === 'paid' ? <Pressable disabled={!canBuy || purchase.isPending || tier.status !== 'open'} onPress={() => purchase.mutate(tier.id)} style={[styles.button, (!canBuy || purchase.isPending || tier.status !== 'open') && styles.disabled]}><Text style={styles.buttonText}>{canBuy ? 'Use Gems for access' : 'Need more Gems'}</Text><Ionicons name="arrow-forward" size={16} color={Colors.black} /></Pressable> : null}</View>; })}</View>;
}

const styles = StyleSheet.create({ wrap: { marginTop: 15, padding: 16, borderRadius: 23, backgroundColor: Colors.gray[900], borderWidth: 1, borderColor: Colors.border }, heading: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'transparent' }, icon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#24160F', marginRight: 11 }, flex: { flex: 1, backgroundColor: 'transparent' }, eyebrow: { color: Colors.primary, fontFamily: 'SpaceMono', fontSize: 7, letterSpacing: .6 }, title: { color: Colors.white, fontSize: 16, fontWeight: '900', marginTop: 3 }, card: { marginTop: 12, padding: 13, borderRadius: BorderRadius.lg, backgroundColor: Colors.black, borderWidth: 1, borderColor: Colors.border }, row: { flexDirection: 'row', backgroundColor: 'transparent' }, type: { color: Colors.primary, fontFamily: 'SpaceMono', fontSize: 6.5 }, name: { color: Colors.white, fontSize: 12, fontWeight: '900', marginTop: 3 }, price: { color: Colors.white, fontSize: 10, fontWeight: '900' }, description: { color: Colors.gray[500], fontSize: 9, lineHeight: 14, marginTop: 8 }, reward: { color: Colors.primary, fontSize: 7, fontWeight: '800', marginTop: 8 }, pass: { padding: 11, marginTop: 10, borderRadius: 12, backgroundColor: Colors.primary }, passLabel: { color: Colors.black, fontSize: 6.5, fontWeight: '900' }, code: { color: Colors.black, fontFamily: 'SpaceMono', fontSize: 10, marginTop: 4 }, button: { minHeight: 42, marginTop: 10, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 13, backgroundColor: Colors.primary }, disabled: { opacity: .35 }, buttonText: { color: Colors.black, fontSize: 9, fontWeight: '900' }, note: { color: Colors.gray[500], fontSize: 8, lineHeight: 13, marginTop: 6 } });
