import { Alert, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/api';
import { Text, View } from '@/components/Themed';
import { ResponsivePressable as Pressable } from '@/components/ResponsivePressable';
import { BorderRadius, Colors } from '@/constants/DesignTokens';

type Item={id:string;title:string;submoment_status?:string;venue_approval_required?:boolean;venue_approval_status?:string};
export function SubMomentGovernance({momentId,momentTitle,location}:{momentId:string;momentTitle:string;location?:string|null}){
 const cache=useQueryClient(); const query=useQuery({queryKey:['submoments',momentId],queryFn:()=>apiRequest<{data:Item[];permissions:{can_review:boolean}}>(`/api/moment-economy/moments/${momentId}/submoments`)});
 const review=useMutation({mutationFn:({id,decision}:{id:string;decision:'approve'|'reject'})=>apiRequest(`/api/moment-economy/moments/${momentId}/submoments/${id}/review`,{method:'POST',body:JSON.stringify({decision})}),onSuccess:()=>cache.invalidateQueries({queryKey:['submoments',momentId]}),onError:(e:Error)=>Alert.alert('Review failed',e.message)});
 const items=query.data?.data||[]; return <View style={s.shell}><Text style={s.eyebrow}>ACTIVITY INSIDE THIS MOMENT</Text><Text style={s.title}>Sub-moments</Text><Text style={s.detail}>Propose a birthday, workshop or creative activity. The host reviews it before publication.</Text><Pressable style={s.create} onPress={()=>router.push({pathname:'/studio/create-moment',params:{parentMomentId:momentId,parentTitle:momentTitle,parentLocation:location||''}} as never)}><Ionicons name="add" size={17} color={Colors.black}/><Text style={s.createText}>Propose activity</Text></Pressable>{items.map(item=><View key={item.id} style={s.item}><Pressable style={s.itemCopy} onPress={()=>router.push(`/moment/${item.id}` as any)}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.detail}>{(item.submoment_status||'proposed').replace('_',' ')}{item.venue_approval_required?` · venue ${item.venue_approval_status||'pending'}`:''}</Text></Pressable>{query.data?.permissions.can_review&&item.submoment_status==='proposed'?<View style={s.actions}><Pressable onPress={()=>review.mutate({id:item.id,decision:'reject'})}><Ionicons name="close-circle" size={26} color={Colors.gray[500]}/></Pressable><Pressable onPress={()=>review.mutate({id:item.id,decision:'approve'})}><Ionicons name="checkmark-circle" size={26} color={Colors.success}/></Pressable></View>:<Ionicons name="chevron-forward" size={18} color={Colors.gray[500]}/>}</View>)}</View>
}
const s=StyleSheet.create({shell:{marginTop:13,padding:16,borderRadius:BorderRadius.xl,backgroundColor:Colors.gray[900],borderWidth:1,borderColor:Colors.border},eyebrow:{color:Colors.primary,fontFamily:'SpaceMono',fontSize:10,letterSpacing:.7},title:{color:Colors.white,fontSize:19,fontWeight:'900',marginTop:4},detail:{color:Colors.gray[500],fontSize:11,lineHeight:16,marginTop:4},create:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,marginTop:13,paddingHorizontal:13,paddingVertical:10,borderRadius:16,backgroundColor:Colors.primary},createText:{color:Colors.black,fontSize:11,fontWeight:'900'},item:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:Colors.border,backgroundColor:'transparent'},itemCopy:{flex:1},itemTitle:{color:Colors.white,fontSize:12,fontWeight:'800'},actions:{flexDirection:'row',gap:7,backgroundColor:'transparent'}});
