import { useState } from "react";
import { CheckCircle2, Clock3, FileCheck2, Gem, KeyRound, LockKeyhole, MapPin, PackageCheck, Radio, ReceiptText, ShieldCheck, Ticket, Trophy } from "lucide-react";

function Header({ number, kicker, title, copy }: { number: string; kicker: string; title: string; copy: string }) {
  return <div className="mb-10 grid gap-6 lg:grid-cols-[1fr_.48fr] lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#ff6a00]">{number} · {kicker}</p><h2 className="mt-4 max-w-5xl font-serif text-5xl font-bold leading-[.9] tracking-[-.055em] md:text-7xl">{title}</h2></div><p className="border-l border-[#ff6a00]/35 pl-5 text-sm leading-6 text-white/48">{copy}</p></div>;
}

function Paper({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <div className={`relative overflow-hidden bg-[#eadcc6] text-[#111] shadow-[0_28px_80px_rgba(0,0,0,.28)] ${className}`} style={{backgroundImage:"repeating-linear-gradient(0deg,transparent 0 25px,rgba(30,20,10,.045) 26px)"}}>{children}</div>;
}

function DiscoveryOps() {
  const [selected, setSelected] = useState(0);
  const lanes = [
    {label:"Live music after dark", count:812, place:"New Kingston", delta:"+18%", responders:2},
    {label:"Late-night food market", count:621, place:"Liguanea", delta:"+9%", responders:1},
    {label:"Creator workshop", count:428, place:"Barbican", delta:"+6%", responders:0},
  ];
  return <section className="border-t border-white/10 pt-20"><Header number="12D" kicker="Discovery · operational artifact" title="Demand is measured, answered, then either becomes real or does not." copy="V4 replaces explanation panels with operational evidence: location, velocity, responders, threshold and supply commitment."/><div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
    <div className="rounded-[2rem] border border-[#ff6a00]/30 bg-[#120b08] p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ff9a4d]">KSN-SIGNAL · 0916</p><h3 className="mt-2 font-serif text-4xl font-bold">What should the city get next?</h3></div><Radio className="text-[#22c55e]"/></div><div className="mt-7 space-y-3">{lanes.map((lane,i)=><button key={lane.label} onClick={()=>setSelected(i)} className={`w-full overflow-hidden rounded-xl border text-left ${selected===i?"border-[#ff6a00]/60 bg-[#ff6a00]/7":"border-white/10"}`}><div className="grid grid-cols-[1fr_auto] gap-5 p-4"><div><p className="font-bold">{lane.label}</p><p className="mt-1 text-xs text-white/42">{lane.place} · {lane.delta} today · {lane.responders} responder{lane.responders===1?"":"s"}</p></div><p className="font-serif text-2xl font-bold text-[#f6c453]">{lane.count}</p></div><div className="h-1 bg-white/5"><div className="h-full bg-[#ff6a00]" style={{width:`${Math.min(100,lane.count/9)}%`}}/></div></button>)}</div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-dashed border-[#ff6a00]/25 pt-5 text-xs"><div><p className="text-white/28">THRESHOLD</p><p className="mt-1 font-bold">1,200 signals</p></div><div><p className="text-white/28">LEAD</p><p className="mt-1 font-bold">{lanes[selected].count}</p></div><div><p className="text-white/28">SUPPLY</p><p className="mt-1 font-bold">Not confirmed</p></div></div></div>
    <div className="grid gap-4"><div className="rounded-[1.5rem] border border-[#4cc6f0]/20 bg-[#071319] p-5"><div className="flex items-center gap-2 text-[#4cc6f0]"><MapPin className="h-4 w-4"/><p className="text-[10px] font-black uppercase tracking-[.17em]">Field trace</p></div><div className="mt-5 space-y-4">{[["New Kingston","812","+18%"],["Liguanea","621","+9%"],["Barbican","428","+6%"]].map(([p,c,d])=><div key={p} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-white/8 pb-3 text-sm"><span>{p}</span><b>{c}</b><span className="text-[#4cc6f0]">{d}</span></div>)}</div></div><div className="rounded-[1.5rem] border border-[#22c55e]/20 bg-[#07120b] p-5"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#22c55e]">Response ledger</p>{[["HR-0021","Sea Deck","Interested · Thu 9 PM","18 min ago"],["CR-0118","Mikey Milli","Interested in hosting","27 min ago"]].map(([id,who,msg,time])=><div key={id} className="mt-4 rounded-xl border border-white/10 p-4"><div className="flex justify-between text-[10px] text-white/35"><span>{id}</span><span>{time}</span></div><p className="mt-2 font-bold">{who}</p><p className="mt-1 text-sm text-white/55">{msg}</p></div>)}</div></div>
  </div></section>;
}

function PieceOps() {
  const [transferred,setTransferred] = useState(false);
  return <section className="border-t border-white/10 pt-20"><Header number="13D" kicker="Pieces · operational artifact" title="A Piece carries stamps because something actually happened to it." copy="The Piece now carries operational residue on the object itself: acquisition, validation, utility and transfer history."/><div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
    <div className="relative overflow-hidden rounded-[1.4rem] border border-[#b58cff]/30 bg-[#17111f] p-8" style={{backgroundImage:"repeating-linear-gradient(0deg,transparent 0 28px,rgba(255,255,255,.025) 29px)"}}><div className="absolute bottom-0 left-16 top-0 w-px bg-[#b58cff]/20"/><div className="pl-12"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#b58cff]">ARCHIVE · P-0042-A · OPENING RUN</p><h3 className="mt-16 max-w-xl font-serif text-4xl font-bold">Piece 0042 — Liguanea Return</h3><p className="mt-3 text-sm text-white/46">Food & Taste collection · origin Broken Plate</p><div className="mt-16 grid gap-3 sm:grid-cols-2">{[["ACQUIRED","EARNED · Sep 18"],["PROOF","Merchant verified · 1:15 PM"],["UTILITY","Food Scene access · Oct 31"],["TRANSFER",transferred?"TRANSFERRED · Sep 22":"NOT TRANSFERRED"]].map(([a,b])=><div key={a} className="border border-white/10 p-4"><p className="text-[9px] font-black tracking-[.16em] text-[#ff9a4d]">{a}</p><p className="mt-2 text-sm font-bold">{b}</p></div>)}</div><button onClick={()=>setTransferred(!transferred)} className="mt-6 rounded-full border border-[#b58cff]/35 px-5 py-3 text-xs font-bold text-[#d8c5ff]">{transferred?"Revert review transfer":"Apply transfer stamp"}</button></div></div>
    <div className="rounded-[1.5rem] border border-white/10 bg-[#0d0d0f] p-6"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#b58cff]">Provenance ledger</p><div className="mt-6 space-y-5">{[["12:04 PM","MOVE","Lunch offer surfaced"],["1:14 PM","RETURN","20% benefit used"],["1:15 PM","PROOF","Merchant validation recorded"],["1:15 PM","KEPT","Piece 0042 created in Vault"],...(transferred?[["Sep 22","TRANSFER","Holder changed · provenance retained"]]:[])].map(([time,k,t])=><div key={`${time}-${k}`} className="grid grid-cols-[90px_90px_1fr] gap-3 border-b border-white/8 pb-4 text-sm"><span className="text-white/30">{time}</span><b className="text-[#ff9a4d]">{k}</b><span>{t}</span></div>)}</div></div>
  </div></section>;
}

function KeyOps() {
  const states=["Locked","Unlocked","Active","Expiring","Used"] as const;
  const [state,setState]=useState<(typeof states)[number]>("Active");
  return <section className="border-t border-white/10 pt-20"><Header number="15D" kicker="PromoKeys · operational artifact" title="The Key itself should visibly change when the threshold is crossed." copy="State selectors no longer do all the work. The access object carries serial, validity, requirement and permanent validation residue."/><div className="grid gap-6 xl:grid-cols-[520px_1fr]"><div><div className="mb-4 flex flex-wrap gap-2">{states.map(s=><button key={s} onClick={()=>setState(s)} className={`rounded-full border px-4 py-2 text-xs font-bold ${state===s?"border-[#ff6a00]/60 bg-[#ff6a00]/10":"border-white/10 text-white/45"}`}>{s}</button>)}</div><div className="relative overflow-hidden border border-[#f6c453]/30 bg-[#110d08] p-7" style={{clipPath:"polygon(0 0,88% 0,88% 8%,100% 8%,100% 92%,88% 92%,88% 100%,0 100%)"}}><div className="flex justify-between"><p className="text-[10px] font-black tracking-[.18em] text-[#ff9a4d]">PROMOKEY · PK-0916-SEA</p><KeyRound className="text-[#f6c453]"/></div><h3 className="mt-16 font-serif text-4xl font-bold">AFTRHRS Wing Key</h3><p className="mt-2 text-sm text-white/50">Sea Deck · complimentary wings</p><div className="mt-12 grid grid-cols-2 gap-4 border-t border-dashed border-[#f6c453]/20 pt-5 text-xs"><div><p className="text-white/28">STATE</p><p className={`mt-1 font-black ${state==="Used"?"text-white/45":"text-[#22c55e]"}`}>{state.toUpperCase()}</p></div><div><p className="text-white/28">VALID</p><p className="mt-1 font-bold">Wed · 10 PM–12 AM</p></div><div><p className="text-white/28">ISSUER</p><p className="mt-1 font-bold">Sea Deck</p></div><div><p className="text-white/28">REQUIRES</p><p className="mt-1 font-bold">Merchant validation</p></div></div>{state==="Used"&&<div className="mt-6 border-2 border-[#ff6a00]/55 p-4 text-center text-xs font-black uppercase tracking-[.22em] text-[#ff9a4d]">VALIDATED · 11:08 PM · SEA-CHK-221</div>}</div></div><div className="rounded-[1.5rem] border border-white/10 p-6"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#f6c453]">Threshold log</p><div className="mt-6 grid gap-3 md:grid-cols-5">{states.map((s,i)=><div key={s} className={`border p-4 ${state===s?"border-[#f6c453]/45 bg-[#f6c453]/6":"border-white/10"}`}><p className="text-[9px] text-[#ff9a4d]">0{i+1}</p><p className="mt-5 font-bold">{s}</p><p className="mt-2 text-xs text-white/38">{["Requirement visible","Object becomes yours","Ready to cross","Urgency appears","Access becomes proof"][i]}</p></div>)}</div></div></div></section>;
}

function PromoShareOps(){
  const states=["Open","Locked","Drawing","Result"] as const; const [state,setState]=useState<(typeof states)[number]>("Open");
  const tickets=["18321","18322","18323","18324","18325","18326"];
  return <section className="border-t border-white/10 pt-20"><Header number="16D" kicker="PromoShare · operational artifact" title="A draw should progress from entry set to immutable result." copy="The stage, ticket batch, lock seal, draw clock and result record now show the lifecycle instead of explaining it."/><div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><div className="overflow-hidden rounded-[2rem] border border-[#f6c453]/30 bg-[#130f07]"><div className="border-b border-[#f6c453]/25 p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#f6c453]">PROMOSHARE · KFD-0916</p><h3 className="mt-3 font-serif text-4xl font-bold">Kingston Food Drop</h3><p className="mt-2 text-sm text-white/45">Dinner for two + AFTRHRS PromoKey</p></div><Trophy className="text-[#f6c453]"/></div><div className="mt-5 flex flex-wrap gap-2">{states.map(s=><button key={s} onClick={()=>setState(s)} className={`rounded-full border px-4 py-2 text-xs font-bold ${state===s?"border-[#f6c453]/55 bg-[#f6c453]/8":"border-white/10 text-white/45"}`}>{s}</button>)}</div></div><div className="p-6"><div className="mb-4 flex justify-between text-sm"><b>{state==="Open"?"6 entries · closes 8 PM":state==="Locked"?"ENTRY SET LOCKED":state==="Drawing"?"DRAWING · 8:02 PM":"RESULT RECORDED"}</b><span className="text-white/35">KFD-0916</span></div><div className="grid gap-2 sm:grid-cols-2">{tickets.map((t,i)=><Paper key={t} className={`border-y-[10px] border-dotted border-[#080809] p-4 ${state==="Result"&&i===4?"ring-2 ring-[#f6c453]":""}`}><div className="flex justify-between text-[9px] uppercase"><span>KINGSTON FOOD DROP</span><span>{["participation","share","share","partner","share","participation"][i]}</span></div><div className="mt-4 flex justify-between font-bold"><span>PS-KFD-{t}</span>{state==="Result"&&i===4&&<span>SELECTED</span>}</div></Paper>)}</div></div></div><div className="rounded-[1.5rem] border border-white/10 p-6"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#f6c453]">Draw audit rail</p><div className="mt-6 space-y-4">{[["NAMED DRAW","Kingston Food Drop · KFD-0916"],["PRIZE","Dinner for two + AFTRHRS PromoKey"],["ENTRY SET","6 tickets · provenance retained"],["CLOSE","8:00 PM · entries lock"],["DRAW","8:02 PM · recorded"],["RESULT",state==="Result"?"PS-KFD-18325 selected":"Pending"]].map(([a,b])=><div key={a} className="grid grid-cols-[120px_1fr] border-b border-white/8 pb-4 text-sm"><b className="text-[9px] tracking-[.15em] text-white/30">{a}</b><span>{b}</span></div>)}</div></div></div></section>;
}

function SaveWinOps(){ const [amount,setAmount]=useState(25); return <section className="border-t border-white/10 pt-20"><Header number="17D" kicker="Save & Win · operational artifact" title="Custody has to be proven, not merely promised." copy="The protected principal now carries an owner/custody ledger while the promotional prize carries separate funding evidence."/><div className="grid gap-6 xl:grid-cols-2"><div className="rounded-[2rem] border border-[#22c55e]/25 bg-[#061309] p-7"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#22c55e]">RESERVE · R-0916 · ANDRE</p><h3 className="mt-3 font-serif text-4xl font-bold">Protected principal</h3></div><LockKeyhole className="text-[#22c55e]"/></div><div className="mt-7 grid grid-cols-3 gap-3">{[10,25,50].map(v=><button key={v} onClick={()=>setAmount(v)} className={`rounded-xl border p-4 font-bold ${amount===v?"border-[#4cc6f0]/55 bg-[#4cc6f0]/8 text-[#4cc6f0]":"border-white/10"}`}>{v}</button>)}</div><div className="mt-6 rounded-xl border border-[#22c55e]/30 p-5"><div className="grid gap-3 text-sm sm:grid-cols-2"><p>Owner <b className="float-right">Andre</b></p><p>Available <b className="float-right">74 Gems</b></p><p>Parked <b className="float-right text-[#22c55e]">{amount} Gems</b></p><p>Status <b className="float-right">Protected</b></p><p>Tickets <b className="float-right">{amount/5}</b></p><p>Return <b className="float-right">After draw</b></p></div><p className="mt-4 border-t border-dashed border-[#22c55e]/25 pt-4 text-xs text-white/45">Still attributable to you · not spent · not part of prize pool.</p></div></div><div className="rounded-[2rem] border border-[#4cc6f0]/25 bg-[#061218] p-7"><Trophy className="text-[#4cc6f0]"/><p className="mt-6 text-[10px] font-black tracking-[.18em] text-[#4cc6f0]">COMMITTED PROMOTIONAL POOL</p><h3 className="mt-3 font-serif text-4xl font-bold">100 extra Gems</h3><div className="mt-7 rounded-xl border border-[#4cc6f0]/25 p-5 text-sm"><p className="border-b border-white/8 pb-3">Funded by <b className="float-right">Partner Pool</b></p><p className="border-b border-white/8 py-3">Committed <b className="float-right">Sep 15</b></p><p className="border-b border-white/8 py-3">Draw <b className="float-right">Weekend 100</b></p><p className="pt-3">Participant principal <b className="float-right text-[#4cc6f0]">NOT USED</b></p></div></div></div></section>; }

function ValueOps(){ const [tab,setTab]=useState<"Gems"|"Points"|"Tickets">("Gems"); return <section className="border-t border-white/10 pt-20"><Header number="18D" kicker="Value · operational artifact" title="Value should leave a ledger trail appropriate to what kind of value it is." copy="Gems use transactions; Points use participation traces; Tickets use named-draw batches. One summary-card treatment is no longer acceptable."/><div className="mb-5 flex gap-2">{(["Gems","Points","Tickets"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-full border px-5 py-2 text-xs font-bold ${tab===t?"border-[#ff6a00]/55 bg-[#ff6a00]/10":"border-white/10 text-white/45"}`}>{t}</button>)}</div>{tab==="Gems"&&<div className="grid gap-6 xl:grid-cols-[.6fr_1.4fr]"><div className="rounded-[1.5rem] border border-[#4cc6f0]/25 bg-[#071319] p-6"><Gem className="text-[#4cc6f0]"/><p className="mt-6 text-5xl font-bold text-[#4cc6f0]">74</p><p className="mt-1 text-sm text-white/42">Spendable platform value</p></div><Paper className="p-6"><p className="text-[10px] font-black uppercase tracking-[.18em]">GEM LEDGER · ANDRE</p>{[["TODAY","Piece purchase","-36"],["YESTERDAY","Save & Win return","+25"],["SEP 14","Merchant reward","+10"]].map(([d,a,v])=><div key={a} className="grid grid-cols-[90px_1fr_auto] border-b border-black/10 py-4 text-sm"><span className="text-black/45">{d}</span><b>{a}</b><b>{v}</b></div>)}</Paper></div>}{tab==="Points"&&<div className="rounded-[1.5rem] border border-[#ff6a00]/25 p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#ff9a4d]">PARTICIPATION TRACE · 1,840</p>{[["+120","Workshop verified"],["+80","Referral completed"],["+40","Discovery signal accepted"]].map(([p,a],i)=><div key={a} className="relative ml-3 border-l border-[#ff6a00]/25 py-5 pl-8"><span className="absolute -left-2 top-7 h-4 w-4 rounded-full bg-[#ff6a00]"/><b className="text-[#f6c453]">{p}</b><span className="ml-4">{a}</span></div>)}</div>}{tab==="Tickets"&&<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[["Kingston Food Drop","6","Closes tonight · 8 PM"],["Weekend 100","5","Draw Saturday"],["Creator Drop","2","Result recorded"]].map(([n,c,s])=><Paper key={n} className="border-y-[10px] border-dotted border-[#080809] p-5"><p className="text-[9px] font-black uppercase tracking-[.17em]">NAMED DRAW</p><h4 className="mt-3 font-serif text-2xl font-bold">{n}</h4><p className="mt-8 text-4xl font-bold">{c}</p><p className="text-xs text-black/50">entries</p><p className="mt-5 border-t border-black/10 pt-4 text-sm">{s}</p></Paper>)}</div>}</section>; }

export function PromorangEconomyLabV4(){ return <div className="space-y-32"><DiscoveryOps/><PieceOps/><KeyOps/><PromoShareOps/><SaveWinOps/><ValueOps/></div>; }
