import { useMemo, useState } from "react";
import {
  ArrowRight,
  BadgeCheck,
  Check,
  CheckCircle2,
  Clock3,
  Gem,
  Gift,
  History,
  KeyRound,
  Layers3,
  Lock,
  MapPin,
  Radio,
  Share2,
  ShieldCheck,
  Sparkles,
  Store,
  Ticket,
  Trophy,
  Vote,
  WalletCards,
} from "lucide-react";
import { PromorangMark } from "@/components/promorang/PromorangMark";

const C = {
  ink: "#080809",
  panel: "#0d0d0f",
  ochre: "#ff6a00",
  clay: "#7a2e17",
  sand: "#eadcc6",
  gold: "#f6c453",
  water: "#4cc6f0",
  leaf: "#22c55e",
  violet: "#b58cff",
  paper: "#f3e8d3",
  paperDeep: "#dfcfb4",
};

type StudyMark = "signal" | "artifact" | "market" | "key" | "draw" | "vault" | "gem" | "points" | "ticket";

function SystemGlyph({ kind, size = 38 }: { kind: StudyMark; size?: number }) {
  const common = { width: size, height: size, viewBox: "0 0 64 64", fill: "none", "aria-hidden": true } as const;
  if (kind === "signal") return <svg {...common}><path d="M8 46C17 25 27 45 38 25C44 14 52 18 57 9" stroke={C.ochre} strokeWidth="4" strokeDasharray="1 8" strokeLinecap="round"/><circle cx="8" cy="46" r="5" fill={C.gold}/><circle cx="38" cy="25" r="5" fill={C.clay}/><circle cx="57" cy="9" r="5" fill={C.ochre}/></svg>;
  if (kind === "artifact") return <svg {...common}><path d="M14 13H50V49H14z" stroke={C.violet} strokeWidth="3"/><path d="M20 22H44M20 30H39M20 38H34" stroke={C.sand} strokeWidth="3" strokeLinecap="round"/><circle cx="47" cy="47" r="10" fill={C.clay} stroke={C.gold} strokeWidth="3"/></svg>;
  if (kind === "market") return <svg {...common}><path d="M11 26L17 14H47L53 26" stroke={C.water} strokeWidth="3"/><path d="M14 27V50H50V27" stroke={C.sand} strokeWidth="3"/><path d="M11 26H53" stroke={C.gold} strokeWidth="3"/><circle cx="32" cy="38" r="5" fill={C.violet}/></svg>;
  if (kind === "key") return <svg {...common}><circle cx="24" cy="29" r="11" stroke={C.gold} strokeWidth="4"/><path d="M33 29H54M45 29V37M51 29V34" stroke={C.ochre} strokeWidth="4" strokeLinecap="round"/><circle cx="24" cy="29" r="3" fill={C.sand}/></svg>;
  if (kind === "draw") return <svg {...common}><path d="M11 17H53V48H11z" stroke={C.gold} strokeWidth="3"/><path d="M22 17V48M42 17V48" stroke={C.ochre} strokeWidth="2" strokeDasharray="3 4"/><circle cx="32" cy="32" r="6" fill={C.ochre}/><path d="M7 24H15M49 40H57" stroke={C.gold} strokeWidth="4" strokeLinecap="round"/></svg>;
  if (kind === "vault") return <svg {...common}><rect x="10" y="11" width="44" height="42" rx="8" stroke={C.leaf} strokeWidth="3"/><circle cx="32" cy="32" r="10" stroke={C.water} strokeWidth="3"/><path d="M32 22V42M22 32H42" stroke={C.gold} strokeWidth="3" strokeLinecap="round"/><path d="M51 20H56V44H51" stroke={C.leaf} strokeWidth="3"/></svg>;
  if (kind === "gem") return <svg {...common}><path d="M14 23L23 12H41L50 23L32 52L14 23z" stroke={C.water} strokeWidth="3"/><path d="M14 23H50M23 12L32 52M41 12L32 52M23 12L14 23M41 12L50 23" stroke={C.water} strokeWidth="2"/></svg>;
  if (kind === "points") return <svg {...common}><path d="M10 44C17 25 28 38 35 21C40 9 51 15 55 10" stroke={C.ochre} strokeWidth="4" strokeLinecap="round"/><circle cx="10" cy="44" r="5" fill={C.clay}/><circle cx="35" cy="21" r="5" fill={C.gold}/><circle cx="55" cy="10" r="5" fill={C.ochre}/></svg>;
  return <svg {...common}><path d="M11 18H53V46H11z" stroke={C.gold} strokeWidth="3"/><path d="M20 18V46M44 18V46" stroke={C.ochre} strokeWidth="2" strokeDasharray="3 4"/><path d="M27 27H37M27 34H37" stroke={C.sand} strokeWidth="3" strokeLinecap="round"/></svg>;
}

function SectionIntro({ number, kicker, title, copy }: { number: string; kicker: string; title: string; copy: string }) {
  return <div className="mb-12 grid gap-7 lg:grid-cols-[1fr_.52fr] lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#ff6a00]">{number} · {kicker}</p><h2 className="mt-4 max-w-5xl font-serif text-5xl font-bold leading-[.9] tracking-[-.055em] text-white md:text-7xl">{title}</h2></div><div className="border-l border-[#ff6a00]/35 pl-5"><p className="text-sm leading-6 text-white/50">{copy}</p></div></div>;
}

function Tabs<T extends string>({ items, active, onChange }: { items: readonly T[]; active: T; onChange: (value: T) => void }) {
  return <div className="flex flex-wrap gap-2">{items.map(item => <button type="button" key={item} onClick={() => onChange(item)} className={`rounded-full border px-3.5 py-2 text-xs font-bold transition ${active === item ? "border-[#ff6a00]/55 bg-[#ff6a00]/10 text-[#ff9a4d]" : "border-white/10 text-white/45 hover:text-white"}`}>{item}</button>)}</div>;
}

function PersonalityStrip({ emotion, object, motion, trust }: { emotion: string; object: string; motion: string; trust: string }) {
  return <div className="mt-8 grid border border-white/10 md:grid-cols-4">{[["Emotion",emotion],["Object",object],["Motion",motion],["Trust",trust]].map(([label,value]) => <div key={label} className="border-white/10 p-5 md:border-r md:last:border-r-0"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#ff6a00]">{label}</p><p className="mt-3 font-serif text-xl font-bold">{value}</p></div>)}</div>;
}

function DiscoveryV2() {
  const [selected, setSelected] = useState(0);
  const choices = [
    { name: "Live music after dark", count: 812, zone: "New Kingston", velocity: "+18% today" },
    { name: "Late-night food market", count: 621, zone: "Liguanea", velocity: "+9% today" },
    { name: "Creator workshop", count: 428, zone: "Barbican", velocity: "+6% today" },
  ];
  const max = Math.max(...choices.map(c => c.count));
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="12B" kicker="Discovery personality" title="A poll becomes a live signal field." copy="Discovery should feel civic, social and unfinished because demand is still forming. The user is not filling out a form; they are adding weight to a visible market signal."/><div className="grid gap-8 xl:grid-cols-[560px_1fr]">
    <div className="overflow-hidden rounded-[2.25rem] border border-[#ff6a00]/25 bg-[radial-gradient(circle_at_20%_0%,rgba(255,106,0,.18),transparent_34%),linear-gradient(180deg,#130c08,#09090a)] shadow-[0_34px_110px_rgba(255,106,0,.09)]">
      <div className="relative overflow-hidden border-b border-white/10 p-6"><div className="absolute right-[-30px] top-[-40px] h-44 w-44 rounded-full border border-[#ff6a00]/20"/><div className="absolute right-[24px] top-[18px] h-24 w-24 rounded-full border border-[#f6c453]/10"/><div className="relative flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#ff8a33]">KINGSTON SIGNAL · LIVE</p><h3 className="mt-3 max-w-[400px] font-serif text-[2.8rem] font-bold leading-[.9]">What should the city get next?</h3></div><SystemGlyph kind="signal" size={54}/></div><div className="mt-5 flex items-center gap-5 text-xs text-white/45"><span className="inline-flex items-center gap-1.5"><Radio className="h-3.5 w-3.5 text-[#22c55e]"/>1,861 signals</span><span>Closes 8 PM</span><span>Kingston</span></div></div>
      <div className="p-6"><p className="mb-4 text-[10px] font-black uppercase tracking-[.17em] text-white/35">Demand lanes</p><div className="space-y-3">{choices.map((choice, index) => { const width = Math.max(32, Math.round((choice.count/max)*100)); const active = selected===index; return <button type="button" onClick={() => setSelected(index)} key={choice.name} className={`relative w-full overflow-hidden rounded-[1.4rem] border p-4 text-left transition ${active ? "border-[#ff6a00]/55 bg-[#ff6a00]/8" : "border-white/10 bg-black/20"}`}><div className="absolute inset-y-0 left-0 bg-gradient-to-r from-[#7a2e17]/38 to-[#ff6a00]/12 transition-all" style={{width:`${width}%`}}/><div className="relative flex items-center justify-between gap-4"><div><p className="text-base font-black">{choice.name}</p><p className="mt-1 text-xs text-white/42">{choice.zone} · {choice.velocity}</p></div><div className="text-right"><p className="text-2xl font-black text-[#f6c453]">{choice.count}</p><p className="text-[9px] uppercase tracking-[.14em] text-white/35">signals</p></div></div></button>; })}</div><button type="button" className="mt-5 flex min-h-13 w-full items-center justify-between rounded-full bg-[#f6c453] px-5 text-sm font-black text-black"><span>Signal this demand</span><ArrowRight className="h-4 w-4"/></button></div>
    </div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-[2rem] border border-[#ff6a00]/20 bg-[#110c09] p-6"><Sparkles className="h-6 w-6 text-[#ff6a00]"/><p className="mt-6 text-[10px] font-black uppercase tracking-[.17em] text-[#ff9a4d]">Momentum</p><h3 className="mt-2 font-serif text-3xl font-bold">Signals should accumulate visibly.</h3><p className="mt-3 text-sm leading-6 text-white/48">Counts, velocity, geography and response readiness should make demand feel alive before supply exists.</p></div><div className="rounded-[2rem] border border-[#4cc6f0]/20 bg-[#081217] p-6"><MapPin className="h-6 w-6 text-[#4cc6f0]"/><p className="mt-6 text-[10px] font-black uppercase tracking-[.17em] text-[#4cc6f0]">Spatial character</p><h3 className="mt-2 font-serif text-3xl font-bold">Demand belongs somewhere.</h3><p className="mt-3 text-sm leading-6 text-white/48">Discovery can show which neighborhoods, Scenes or circles are pulling hardest without pretending that interest is confirmed supply.</p></div><div className="md:col-span-2 rounded-[2rem] border border-[#22c55e]/18 bg-[#0a130d] p-6"><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#22c55e]">Activation threshold</p><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Signal","1,861"],["Pattern","812 lead"],["Response","2 hosts"],["Moment","not yet"]].map(([a,b],i)=><div key={a} className="rounded-2xl border border-white/10 p-4"><p className="text-[9px] font-black uppercase tracking-[.15em] text-white/35">0{i+1} · {a}</p><p className="mt-3 text-xl font-black">{b}</p></div>)}</div></div></div>
  </div><PersonalityStrip emotion="Influence + curiosity" object="Live signal field" motion="Accumulate + tip" trust="Demand ≠ supply"/></section>;
}

function PiecesV2() {
  const [face, setFace] = useState<"Artifact"|"Provenance">("Artifact");
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="13B" kicker="Pieces personality" title="A Piece should feel archived, carried, and storied." copy="Pieces get a tactile archival identity: edition marks, provenance spine, acquisition origin and a physical-feeling artifact face. Earned participation must read differently from marketplace acquisition."/><Tabs items={["Artifact","Provenance"] as const} active={face} onChange={setFace}/><div className="mt-7 grid gap-8 xl:grid-cols-[1fr_500px]">
    {face === "Artifact" ? <div className="relative overflow-hidden rounded-[2.5rem] border border-[#b58cff]/35 bg-[radial-gradient(circle_at_82%_18%,rgba(181,140,255,.22),transparent_28%),linear-gradient(135deg,#17101d,#0b090d_62%,#241529)] p-8 shadow-[0_36px_110px_rgba(98,64,128,.22)]"><div className="absolute left-0 top-0 h-full w-[18px] bg-[repeating-linear-gradient(180deg,#b58cff_0_2px,transparent_2px_11px)] opacity-35"/><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#cdb5ff]">ARCHIVE · PIECE 0042 · EARNED</p><p className="mt-2 text-xs text-white/38">Owned by Andre · First holder</p></div><SystemGlyph kind="artifact" size={64}/></div><div className="mt-24 max-w-2xl"><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#b58cff]">FOOD & TASTE · OPENING RUN</p><h3 className="mt-3 font-serif text-5xl font-bold leading-[.93]">Liguanea Lunch Return</h3><p className="mt-4 max-w-xl text-sm leading-6 text-white/52">A verified use at Broken Plate became a kept cultural record tied to Food & Taste.</p></div><div className="mt-16 grid gap-4 border-t border-[#b58cff]/20 pt-5 sm:grid-cols-4">{[["Origin","Broken Plate"],["Proof","Verified use"],["Acquired","Participation"],["Utility","Food Scene access"]].map(([a,b])=><div key={a}><p className="text-[9px] font-black uppercase tracking-[.14em] text-white/28">{a}</p><p className="mt-2 text-sm font-bold">{b}</p></div>)}</div><div className="mt-7 flex items-center justify-between rounded-2xl border border-white/10 bg-black/20 p-4"><div><p className="text-[9px] font-black uppercase tracking-[.14em] text-[#cdb5ff]">Archive seal</p><p className="mt-1 text-sm font-bold">Provenance attached permanently</p></div><BadgeCheck className="h-6 w-6 text-[#b58cff]"/></div></div> : <div className="rounded-[2.5rem] border border-[#eadcc6]/20 bg-[#0c0b0d] p-8"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#b58cff]">PROVENANCE SPINE</p><h3 className="mt-3 font-serif text-4xl font-bold">The story survives ownership.</h3><div className="mt-9 border-l border-[#b58cff]/30 pl-7">{[["MOVE","Lunch offer surfaced","Sep 18 · 12:04 PM"],["RETURN","20% benefit used","Sep 18 · 1:14 PM"],["PROOF","Merchant validated use","Sep 18 · 1:15 PM"],["KEPT","Piece 0042 minted","Sep 18 · 1:15 PM"],["MARKET","Not listed","Current state"]].map(([a,b,c],i)=><div key={a} className="relative pb-8 last:pb-0"><span className="absolute -left-[35px] top-1 h-4 w-4 rounded-full border-2 border-[#b58cff] bg-[#0c0b0d]"/><p className="text-[9px] font-black uppercase tracking-[.14em] text-[#cdb5ff]">{a}</p><p className="mt-1 text-lg font-bold">{b}</p><p className="mt-1 text-xs text-white/35">{c}</p></div>)}</div></div>}
    <div className="rounded-[2.25rem] border border-white/10 bg-[#0d0d0f] p-7"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ff6a00]">Collection identity</p><h3 className="mt-3 font-serif text-3xl font-bold">Pieces should cluster into cultural series.</h3><div className="mt-7 space-y-3">{[["Food & Taste","3 kept","#b58cff"],["Kingston After Dark","2 kept","#ff6a00"],["Move Jamaica","1 kept","#4cc6f0"]].map(([a,b,color])=><div key={a} className="flex items-center justify-between rounded-2xl border border-white/10 p-4"><div className="flex items-center gap-3"><span className="h-9 w-2 rounded-full" style={{background:color}}/><div><p className="font-bold">{a}</p><p className="mt-1 text-xs text-white/35">Series</p></div></div><p className="text-sm font-black">{b}</p></div>)}</div><div className="mt-6 rounded-2xl border border-[#f6c453]/18 bg-[#f6c453]/5 p-4"><p className="text-xs font-bold text-[#f6c453]">Earned ≠ bought</p><p className="mt-2 text-xs leading-5 text-white/48">Acquisition origin should remain visible even after sale or transfer.</p></div></div>
  </div><PersonalityStrip emotion="Pride + memory" object="Archival artifact" motion="Accumulate + preserve" trust="Provenance survives transfer"/></section>;
}

function MarketplaceV2() {
  const [selected, setSelected] = useState(0);
  const pieces = [{id:"0118",name:"Barbican Night Signal",series:"Kingston After Dark",ask:36,origin:"Earned · Aug 30"},{id:"0207",name:"Move Jamaica First Drive",series:"Move Jamaica",ask:42,origin:"Earned · Sep 03"},{id:"0315",name:"New Kingston Room",series:"Community",ask:24,origin:"Marketplace · Sep 10"}];
  const item = pieces[selected];
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="14B" kicker="Marketplace personality" title="The market should feel like a gallery with an exchange desk." copy="Browse can be visual and collectible; settlement must become sober, explicit and trust-heavy. PROMORANG should never look like a speculative trading terminal."/><div className="grid gap-8 xl:grid-cols-[1fr_480px]">
    <div className="rounded-[2.25rem] border border-[#b58cff]/20 bg-[#0c0b0e] p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#b58cff]">PIECE MARKET · KINGSTON</p><h3 className="mt-2 font-serif text-4xl font-bold">Objects in circulation.</h3></div><div className="rounded-full border border-[#4cc6f0]/25 bg-[#4cc6f0]/6 px-4 py-2 text-sm font-black text-[#4cc6f0]">74 Gems</div></div><div className="mt-7 grid gap-4 lg:grid-cols-3">{pieces.map((p,index)=><button type="button" key={p.id} onClick={()=>setSelected(index)} className={`group min-h-[280px] rounded-[1.8rem] border p-5 text-left transition ${selected===index?"border-[#b58cff]/60 bg-[#b58cff]/8":"border-white/10 bg-black/20"}`}><div className="flex items-start justify-between"><SystemGlyph kind="artifact" size={40}/><span className="text-[9px] font-black uppercase tracking-[.16em] text-[#cdb5ff]">{p.id}</span></div><div className="mt-16"><p className="text-[9px] font-black uppercase tracking-[.14em] text-white/32">{p.series}</p><h4 className="mt-2 font-serif text-2xl font-bold leading-[1]">{p.name}</h4><p className="mt-3 text-xs text-white/38">{p.origin}</p></div><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-4"><span className="text-sm font-black text-[#4cc6f0]">{p.ask} Gems</span><ArrowRight className="h-4 w-4 text-white/30 transition group-hover:translate-x-1"/></div></button>)}</div></div>
    <div className="overflow-hidden rounded-[2.25rem] border border-[#4cc6f0]/25 bg-[#081116]"><div className="border-b border-[#4cc6f0]/15 p-6"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#4cc6f0]">VERIFIED EXCHANGE SHEET</p><ShieldCheck className="h-5 w-5 text-[#4cc6f0]"/></div><h3 className="mt-3 font-serif text-3xl font-bold">{item.name}</h3><p className="mt-2 text-sm text-white/42">Piece {item.id} · {item.series}</p></div><div className="p-6"><div className="space-y-4">{[["Provenance",item.origin],["Current holder","Verified participant"],["Utility","Scene access active"],["Ask",`${item.ask} Gems`],["Platform fee","2 Gems"],["Your balance","74 Gems"]].map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-white/8 pb-3 last:border-0"><span className="text-xs text-white/35">{a}</span><span className="text-sm font-bold">{b}</span></div>)}</div><button type="button" className="mt-6 flex min-h-13 w-full items-center justify-between rounded-full bg-[#4cc6f0] px-5 text-sm font-black text-black"><span>Review acquisition</span><ArrowRight className="h-4 w-4"/></button><p className="mt-4 text-xs leading-5 text-white/38">Buying transfers ownership; it does not alter the Piece's origin or guarantee future value.</p></div></div>
  </div><PersonalityStrip emotion="Discernment + trust" object="Gallery + exchange sheet" motion="Inspect + settle" trust="Provenance before price"/></section>;
}

function PromoKeyV2() {
  const [state, setState] = useState<"Locked"|"Unlocked"|"Active"|"Expiring"|"Used">("Active");
  const copy = useMemo(()=>({Locked:["Complete one Food & Taste return","1 requirement remains"],Unlocked:["Key is yours","Activation terms ready"],Active:["Ready at Sea Deck","Wed · 10 PM–12 AM"],Expiring:["Use within 2h 14m","Merchant validation required"],Used:["Returned as Proof","Validated 11:08 PM"]} as const)[state],[state]);
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="15B" kicker="PromoKey personality" title="A Key should look like something that opens a door." copy="PromoKeys become compact access instruments with a notch, lock/unlock ritual and stronger physical silhouette. They should never be mistaken for PromoCard, a coupon, or a balance tile."/><Tabs items={["Locked","Unlocked","Active","Expiring","Used"] as const} active={state} onChange={setState}/><div className="mt-7 grid gap-8 xl:grid-cols-[520px_1fr]">
    <div className={`relative overflow-hidden rounded-[2.2rem] border p-0 shadow-[0_34px_90px_rgba(0,0,0,.45)] ${state==="Used"?"border-white/10 bg-[#111]":"border-[#f6c453]/35 bg-[radial-gradient(circle_at_88%_18%,rgba(246,196,83,.18),transparent_28%),linear-gradient(145deg,#171008,#0a0a0a_68%)]"}`}><div className="absolute right-[-26px] top-[70px] h-14 w-14 rounded-full bg-[#080809] ring-1 ring-[#f6c453]/25"/><div className="p-7"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><PromorangMark size={34}/><div><p className="text-[10px] font-black uppercase tracking-[.19em] text-[#ff9a4d]">PROMOKEY · SEA DECK</p><p className="mt-1 text-xs text-white/35">KEY 82-AFTR</p></div></div><SystemGlyph kind="key" size={52}/></div><div className="mt-20"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#f6c453]">{state}</p><h3 className="mt-3 font-serif text-4xl font-bold">AFTRHRS Wing Key</h3><p className="mt-3 text-sm text-white/48">Complimentary wings · issued through Food & Taste</p></div><div className="mt-8 rounded-[1.5rem] border border-white/10 bg-black/25 p-5"><div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${state==="Active"?"bg-[#22c55e]":state==="Expiring"?"bg-[#f6c453]":state==="Used"?"bg-white/30":"bg-[#ff6a00]"}`}/><p className="font-serif text-2xl font-bold">{copy[0]}</p></div><p className="mt-2 text-sm text-white/42">{copy[1]}</p></div><button type="button" className="mt-6 flex min-h-13 w-full items-center justify-between rounded-full bg-[#eadcc6] px-5 text-sm font-black text-black"><span>{state==="Locked"?"See unlock path":state==="Used"?"View returned proof":"Show Key"}</span><KeyRound className="h-4 w-4"/></button></div></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-[2rem] border border-[#f6c453]/20 bg-[#171207] p-6"><Lock className="h-6 w-6 text-[#f6c453]"/><p className="mt-6 text-[10px] font-black uppercase tracking-[.16em] text-[#f6c453]">Unlock ritual</p><h3 className="mt-2 font-serif text-3xl font-bold">Access is earned or granted.</h3><p className="mt-3 text-sm leading-6 text-white/48">Locked Keys show exactly what opens them; unlocked Keys reveal terms before activation.</p></div><div className="rounded-[2rem] border border-[#4cc6f0]/20 bg-[#071319] p-6"><CheckCircle2 className="h-6 w-6 text-[#4cc6f0]"/><p className="mt-6 text-[10px] font-black uppercase tracking-[.16em] text-[#4cc6f0]">Return ritual</p><h3 className="mt-2 font-serif text-3xl font-bold">Used access becomes history.</h3><p className="mt-3 text-sm leading-6 text-white/48">After validation, the Key stops acting like access and returns as Proof in Vault / You.</p></div><div className="md:col-span-2 rounded-[2rem] border border-white/10 p-6"><p className="text-[10px] font-black uppercase tracking-[.16em] text-white/32">Key classes</p><div className="mt-4 grid gap-3 sm:grid-cols-4">{["PERK KEY","ENTRY KEY","TIME KEY","COMPANION KEY"].map((label,i)=><div key={label} className="rounded-2xl border border-white/10 p-4"><p className="text-[9px] font-black text-[#ff9a4d]">0{i+1}</p><p className="mt-4 text-sm font-bold">{label}</p></div>)}</div></div></div>
  </div><PersonalityStrip emotion="Privilege + readiness" object="Notched access instrument" motion="Unlock + reveal + validate" trust="Issuer + terms before use"/></section>;
}

function PromoShareV2() {
  const [phase, setPhase] = useState<"Open"|"Closing"|"Drawing"|"Result">("Open");
  const tickets = ["KF-84021","KF-84022","KF-84109","KF-84311","KF-84312","KF-85002"];
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="16B" kicker="PromoShare personality" title="PromoShare should feel like a named event, not a balance card." copy="Each draw becomes its own campaign vessel with marquee identity, countdown, serialized entries, ticket provenance and a result ritual. Theatre comes from anticipation; trust comes from the audit trail."/><Tabs items={["Open","Closing","Drawing","Result"] as const} active={phase} onChange={setPhase}/><div className="mt-7 overflow-hidden rounded-[2.5rem] border border-[#f6c453]/30 bg-[#0d0b08] shadow-[0_38px_120px_rgba(246,196,83,.09)]">
    <div className="relative overflow-hidden border-b border-[#f6c453]/20 bg-[radial-gradient(circle_at_50%_-30%,rgba(246,196,83,.22),transparent_46%),linear-gradient(180deg,#2a1607,#100b07)] px-7 py-8"><div className="absolute inset-x-0 top-0 h-2 bg-[repeating-linear-gradient(90deg,#f6c453_0_22px,#ff6a00_22px_44px)] opacity-80"/><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-3"><SystemGlyph kind="draw" size={48}/><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#f6c453]">PROMOSHARE · KINGSTON · DRAW PS-KFD-0916</p></div><h3 className="mt-5 font-serif text-5xl font-bold leading-[.9]">Kingston Food Drop</h3><p className="mt-4 text-lg text-white/62">Dinner for two + AFTRHRS PromoKey</p></div><div className="rounded-[1.8rem] border border-[#f6c453]/30 bg-black/30 p-5 text-center"><p className="text-[9px] font-black uppercase tracking-[.18em] text-white/35">{phase === "Result" ? "RESULT" : "CLOSES IN"}</p><p className="mt-2 font-serif text-4xl font-bold text-[#f6c453]">{phase==="Open"?"02:14:31":phase==="Closing"?"00:08:42":phase==="Drawing"?"LIVE":"KF-84312"}</p></div></div></div>
    <div className="grid lg:grid-cols-[1fr_420px]"><div className="p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#ff9a4d]">Your draw tickets</p><h4 className="mt-2 font-serif text-3xl font-bold">6 entries in this draw.</h4></div><Ticket className="h-6 w-6 text-[#f6c453]"/></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{tickets.map((ticket,index)=><div key={ticket} className={`relative overflow-hidden rounded-[1.3rem] border p-4 ${phase==="Result"&&ticket==="KF-84312"?"border-[#22c55e]/50 bg-[#22c55e]/8":"border-[#f6c453]/20 bg-[#15100a]"}`}><div className="absolute bottom-[-8px] left-[28%] h-4 w-4 rounded-full bg-[#0d0b08]"/><div className="absolute bottom-[-8px] right-[28%] h-4 w-4 rounded-full bg-[#0d0b08]"/><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#f6c453]">ENTRY {String(index+1).padStart(2,"0")}</p><p className="mt-3 font-mono text-sm font-bold">{ticket}</p><p className="mt-3 text-[10px] text-white/38">{index<2?"Participation":index<5?"Sharing":"Partner action"}</p>{phase==="Result"&&ticket==="KF-84312"?<p className="mt-3 text-xs font-black text-[#22c55e]">WINNING TICKET</p>:null}</div>)}</div><button type="button" className="mt-6 flex min-h-13 w-full items-center justify-between rounded-full bg-[#f6c453] px-5 text-sm font-black text-black"><span>{phase==="Result"?"View result record":"Share for another ticket"}</span><Share2 className="h-4 w-4"/></button></div><div className="border-t border-[#f6c453]/15 bg-black/18 p-7 lg:border-l lg:border-t-0"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#f6c453]">Audit trail</p><div className="mt-5 space-y-4">{[["Prize named","Dinner + PromoKey"],["Draw identity","PS-KFD-0916"],["Ticket set","Locks at 8 PM"],["Ticket sources","2 participation · 3 share · 1 partner"],["Result record",phase==="Result"?"Recorded":"Pending"],["Claim state",phase==="Result"?"Available if winner":"Not available"]].map(([a,b])=><div key={a} className="border-b border-white/8 pb-3 last:border-0"><p className="text-[9px] uppercase tracking-[.13em] text-white/28">{a}</p><p className="mt-1 text-sm font-bold">{b}</p></div>)}</div></div></div>
  </div><PersonalityStrip emotion="Suspense + ceremony" object="Named draw + serialized ticket" motion="Countdown + lock + reveal" trust="Every entry auditable"/></section>;
}

function SaveWinV2() {
  const [amount, setAmount] = useState(25);
  const tickets = amount/5;
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="17B" kicker="Save & Win personality" title="Protected principal and prize theatre must never blur." copy="Save & Win gets its own secure-vault personality. The participant's Gems live in a protected chamber; the committed prize sits in a separate chamber with a different visual language."/><div className="grid gap-8 xl:grid-cols-[1fr_1fr]">
    <div className="rounded-[2.5rem] border border-[#22c55e]/25 bg-[radial-gradient(circle_at_18%_0%,rgba(34,197,94,.13),transparent_36%),#09110c] p-7 shadow-[0_34px_110px_rgba(34,197,94,.07)]"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#22c55e]">PROTECTED PRINCIPAL</p><h3 className="mt-2 font-serif text-4xl font-bold">Still yours.</h3></div><SystemGlyph kind="vault" size={58}/></div><div className="mt-8 rounded-[2rem] border border-[#22c55e]/20 bg-black/20 p-6"><div className="flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[.14em] text-white/30">Your Gems</p><p className="mt-2 text-5xl font-black text-[#4cc6f0]">74</p></div><div className="text-right"><p className="text-[9px] uppercase tracking-[.14em] text-white/30">Parked</p><p className="mt-2 text-4xl font-black text-[#22c55e]">{amount}</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-[#4cc6f0] to-[#22c55e]" style={{width:`${Math.min(100,(amount/74)*100)}%`}}/></div><p className="mt-3 text-xs text-white/42">Parking does not visually or economically behave like spending.</p></div><div className="mt-6"><p className="text-[10px] font-black uppercase tracking-[.15em] text-white/35">Choose Gems to park</p><div className="mt-3 grid grid-cols-3 gap-3">{[10,25,50].map(n=><button key={n} type="button" onClick={()=>setAmount(n)} className={`rounded-2xl border p-4 text-xl font-black ${amount===n?"border-[#4cc6f0]/55 bg-[#4cc6f0]/10 text-[#4cc6f0]":"border-white/10"}`}>{n}</button>)}</div></div></div>
    <div className="rounded-[2.5rem] border border-[#4cc6f0]/25 bg-[radial-gradient(circle_at_80%_0%,rgba(76,198,240,.15),transparent_34%),#081015] p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#4cc6f0]">COMMITTED PRIZE CHAMBER</p><h3 className="mt-2 font-serif text-4xl font-bold">Weekend 100 Gem Pot</h3></div><Trophy className="h-9 w-9 text-[#4cc6f0]"/></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-[1.6rem] border border-[#4cc6f0]/20 p-5"><p className="text-[9px] uppercase tracking-[.14em] text-white/30">Additional prize</p><p className="mt-3 text-4xl font-black text-[#4cc6f0]">100</p><p className="mt-1 text-xs text-white/35">committed Gems</p></div><div className="rounded-[1.6rem] border border-[#f6c453]/20 p-5"><p className="text-[9px] uppercase tracking-[.14em] text-white/30">Your draw entries</p><p className="mt-3 text-4xl font-black text-[#f6c453]">{tickets}</p><p className="mt-1 text-xs text-white/35">named-draw tickets</p></div></div><div className="mt-6 rounded-[1.6rem] border border-white/10 p-5"><p className="text-xs font-bold">Separation statement</p><p className="mt-2 text-sm leading-6 text-white/48">Your parked {amount} Gems remain attributable to you. The 100-Gem prize is a separately committed pool; winning does not come from another participant's parked principal.</p></div><button type="button" className="mt-6 flex min-h-13 w-full items-center justify-between rounded-full bg-[#4cc6f0] px-5 text-sm font-black text-black"><span>Review protected parking</span><ArrowRight className="h-4 w-4"/></button></div>
  </div><PersonalityStrip emotion="Safety + possibility" object="Protected vault + prize chamber" motion="Park + hold + return" trust="Principal visually separated"/></section>;
}

function ValueV2() {
  const [active, setActive] = useState<"Gems"|"Points"|"Tickets">("Gems");
  return <section className="border-t border-white/10 pt-24"><SectionIntro number="18B" kicker="Value personalities" title="Three values. Three different worlds." copy="Gems, Points and Tickets now use different materials, actions and histories. Their UI should teach their meaning without requiring explanatory copy every time they appear."/><Tabs items={["Gems","Points","Tickets"] as const} active={active} onChange={setActive}/><div className="mt-7 grid gap-6 xl:grid-cols-3">
    <button type="button" onClick={()=>setActive("Gems")} className={`min-h-[410px] rounded-[2.4rem] border p-7 text-left transition ${active==="Gems"?"border-[#4cc6f0]/55 bg-[radial-gradient(circle_at_85%_10%,rgba(76,198,240,.18),transparent_28%),#071116] shadow-[0_30px_90px_rgba(76,198,240,.08)]":"border-[#4cc6f0]/18 bg-[#091013]"}`}><SystemGlyph kind="gem" size={54}/><p className="mt-8 text-[10px] font-black uppercase tracking-[.2em] text-[#4cc6f0]">SPENDABLE VALUE</p><h3 className="mt-2 font-serif text-4xl font-bold">Gems</h3><p className="mt-4 text-5xl font-black text-[#4cc6f0]">74</p><p className="mt-2 text-sm text-white/42">Spend · receive · park · transact</p><div className="mt-8 space-y-3 border-t border-[#4cc6f0]/15 pt-5">{[["Piece purchase","−36"],["Save & Win return","+25"],["Merchant reward","+10"]].map(([a,b])=><div key={a} className="flex justify-between text-sm"><span>{a}</span><span className="font-black text-[#4cc6f0]">{b}</span></div>)}</div></button>
    <button type="button" onClick={()=>setActive("Points")} className={`min-h-[410px] rounded-[2.4rem] border p-7 text-left transition ${active==="Points"?"border-[#ff6a00]/55 bg-[radial-gradient(circle_at_85%_10%,rgba(255,106,0,.17),transparent_28%),#140c07] shadow-[0_30px_90px_rgba(255,106,0,.08)]":"border-[#ff6a00]/18 bg-[#100c09]"}`}><SystemGlyph kind="points" size={54}/><p className="mt-8 text-[10px] font-black uppercase tracking-[.2em] text-[#ff9a4d]">PARTICIPATION TRACE</p><h3 className="mt-2 font-serif text-4xl font-bold">Points</h3><p className="mt-4 text-5xl font-black text-[#ff9a4d]">1,840</p><p className="mt-2 text-sm text-white/42">Earn · progress · qualify</p><div className="mt-8 grid grid-cols-3 gap-2 border-t border-[#ff6a00]/15 pt-5">{[["Returns","820"],["Signals","560"],["Shares","460"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/8 p-3"><p className="text-[9px] text-white/28">{a}</p><p className="mt-2 font-black">{b}</p></div>)}</div></button>
    <button type="button" onClick={()=>setActive("Tickets")} className={`min-h-[410px] rounded-[2.4rem] border p-7 text-left transition ${active==="Tickets"?"border-[#f6c453]/55 bg-[radial-gradient(circle_at_85%_10%,rgba(246,196,83,.17),transparent_28%),#151006] shadow-[0_30px_90px_rgba(246,196,83,.08)]":"border-[#f6c453]/18 bg-[#120f09]"}`}><SystemGlyph kind="ticket" size={54}/><p className="mt-8 text-[10px] font-black uppercase tracking-[.2em] text-[#f6c453]">NAMED DRAW ENTRIES</p><h3 className="mt-2 font-serif text-4xl font-bold">Tickets</h3><p className="mt-4 text-5xl font-black text-[#f6c453]">11</p><p className="mt-2 text-sm text-white/42">Enter · lock · result · archive</p><div className="mt-8 space-y-3 border-t border-[#f6c453]/15 pt-5">{[["Kingston Food Drop","6"],["Weekend 100 Gem Pot","5"]].map(([a,b])=><div key={a} className="flex items-center justify-between rounded-xl border border-white/8 p-3"><span className="text-sm">{a}</span><span className="font-black text-[#f6c453]">{b}</span></div>)}</div></button>
  </div><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Gems","Capability","Spendable ledger · monetary-style history"],["Points","Progress","Participation trail · milestones and eligibility"],["Tickets","Chance","Grouped by named draw · result-bound history"]].map(([a,b,c])=><div key={a} className="rounded-[1.5rem] border border-white/10 p-5"><p className="text-[10px] font-black uppercase tracking-[.15em] text-white/32">{a}</p><h4 className="mt-3 font-serif text-2xl font-bold">{b}</h4><p className="mt-2 text-sm leading-6 text-white/45">{c}</p></div>)}</div><PersonalityStrip emotion="Capability / progress / chance" object="Ledger / trail / entry" motion="Spend / accumulate / resolve" trust="Different histories"/></section>;
}

export function PromorangEconomyLabV2() {
  return <div className="space-y-28"><div className="grid gap-6 lg:grid-cols-[1fr_.52fr] lg:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#ff6a00]">PROMORANG ECONOMY · PERSONALITY SEPARATION PASS</p><h2 className="mt-4 max-w-5xl font-serif text-5xl font-bold leading-[.9] tracking-[-.055em] text-white md:text-7xl">One world. Different species.</h2></div><div className="border-l border-[#ff6a00]/35 pl-5"><p className="font-serif text-2xl font-bold text-[#f6d48a]">Recognizable before readable.</p><p className="mt-3 text-sm leading-6 text-white/45">Shared PROMORANG grammar remains. Object silhouette, material, motion and emotional job now separate the subsystems.</p></div></div><DiscoveryV2/><PiecesV2/><MarketplaceV2/><PromoKeyV2/><PromoShareV2/><SaveWinV2/><ValueV2/></div>;
}
