import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { translations } from "@/i18n/translations";
import { fireEvent, render, screen, cleanup } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
vi.mock("@/lib/platform-funnels", () => ({ captureBusinessBrief: vi.fn().mockResolvedValue({ saved: true, leadId: "saved-lead" }), funnelRequest: vi.fn().mockResolvedValue(null) }));
vi.mock("@/i18n/I18nContext", () => ({ useI18n: () => ({ t: (key: keyof typeof translations.en, vars: Record<string, string | number> = {}) => translations.en[key].replace(/\{\{(\w+)\}\}/g, (_, name) => String(vars[name] ?? name)) }) }));
const state = vi.hoisted(() => ({ user: null as null | { id: string }, track: vi.fn() }));
vi.mock("@/contexts/AuthContext", () => ({ useAuth: () => ({ user: state.user }) }));
vi.mock("@/contexts/MarketContext", () => ({ useMarket: () => ({ city: { name: "Kingston" } }) }));
vi.mock("@/lib/marketing-attribution", () => ({ trackGrowthEvent: state.track }));
import { BusinessOutcomeNavigator } from "./BusinessOutcomeNavigator";
import { BUSINESS_OUTCOMES, BUSINESS_TYPES, SUCCESS_ACTIONS, readBusinessOutcomeBrief } from "@/lib/business-outcomes";
afterEach(cleanup);
beforeEach(() => { sessionStorage.clear(); localStorage.clear(); state.user = null; state.track.mockClear(); });
const mount = (path = "/business/start") => render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><MemoryRouter initialEntries={[path]}><BusinessOutcomeNavigator /></MemoryRouter></QueryClientProvider>);
it("keeps abandoned anonymous notes local and restores the completed merchant brief through auth and refresh", async () => {
 const fetcher=vi.spyOn(globalThis,"fetch");
 let view=mount();
 fireEvent.click(screen.getByRole("button",{name:new RegExp(BUSINESS_OUTCOMES[0].title)}));
 const merchant = BUSINESS_TYPES.find(b=>b.id==='place') || BUSINESS_TYPES[0];
 fireEvent.click(screen.getByRole("button",{name:new RegExp(merchant.title)}));
 fireEvent.click(screen.getByRole("button",{name:SUCCESS_ACTIONS[0].title}));
 fireEvent.change(screen.getByPlaceholderText("Who should take this action?"),{target:{value:"Private customer notes"}});
 expect(fetcher).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole("button",{name:/Build my route/}));
 fireEvent.change(screen.getByLabelText(translations.en["funnel.name"]), { target: { value: "Test Merchant" } });
 fireEvent.change(screen.getByLabelText(translations.en["funnel.email"]), { target: { value: "test@example.com" } });
 fireEvent.click(screen.getByRole("button", { name: translations.en["funnel.save"] }));
 await screen.findByRole("link", { name: /Save and continue/ });
 const saved=readBusinessOutcomeBrief(); expect(saved?.audience).toBe("Private customer notes");
 const link=screen.getByRole("link",{name:/Save and continue/});
 expect(link.getAttribute("href")).toContain("resume%3D1");
 fireEvent.click(link);
 view.unmount(); state.user={id:"merchant"};
 view=mount("/business/start?resume=1");
 expect(screen.getByRole("link",{name:/Customize this programme/}).getAttribute("href")).toBe("/offers?from=business-outcome");
 view.unmount(); mount("/business/start?resume=1");
 expect(readBusinessOutcomeBrief()?.id).toBe(saved?.id);
 expect(JSON.stringify(state.track.mock.calls)).not.toContain("Private customer notes");
 expect(fetcher).not.toHaveBeenCalled(); fetcher.mockRestore();
});
