import type { Locale } from "./translations";

type LegalDocument = { title: string; seo: string; updated: string; sections: Array<{ title: string; paragraphs: string[]; id?: string }> };

export const privacyContent: Record<Locale, LegalDocument> = {
  en: { title: "Privacy Policy", seo: "How we handle your data and protect your privacy.", updated: "Last updated: July 14, 2026", sections: [
    { title: "1. Information We Collect", paragraphs: ["We collect information you provide directly, including name, email, profile data, support requests, content, and proof photos. We also process participation, transaction, device, notification-token, and approximate or user-provided location information when needed to operate and verify Moments."] },
    { title: "2. How We Use Information", paragraphs: ["We use information to authenticate accounts, operate and secure the platform, facilitate eligible payments and payouts, verify activation completion, moderate user-generated content, prevent fraud, send requested notifications, and personalize discovery."] },
    { title: "3. Data Sharing", paragraphs: ["We share limited information with brands, hosts, creators, and merchants involved in Moments you join, and with service providers that help operate Promorang. We do not sell personal data."] },
    { title: "4. Security", paragraphs: ["We implement industry-standard security measures to protect your data, though no internet transmission method is completely secure."] },
    { title: "5. Your Rights", paragraphs: ["You may access or correct profile information through account settings and request deletion through the mobile app or account deletion page. Shared user-generated content is included unless retention is legally required."] },
    { title: "6. Retention", paragraphs: ["We retain personal data only as long as needed for the purposes described here. Certain transaction, payout, tax, fraud-prevention, dispute, and regulatory records may be retained where required by law or needed to protect the platform and its users."] },
    { title: "7. Contact", paragraphs: ["Questions and privacy requests can be sent to support@promorang.co."] },
  ] },
  "es-419": { title: "Política de Privacidad", seo: "Cómo tratamos tus datos y protegemos tu privacidad.", updated: "Última actualización: 14 de julio de 2026", sections: [
    { title: "1. Información que recopilamos", paragraphs: ["Recopilamos la información que proporcionas directamente, como nombre, correo, datos del perfil, solicitudes de soporte, contenido y fotos de prueba. También procesamos información de participación, transacciones, dispositivos, notificaciones y ubicación aproximada o proporcionada cuando es necesaria para operar y verificar Momentos."] },
    { title: "2. Cómo usamos la información", paragraphs: ["Usamos la información para autenticar cuentas, operar y proteger la plataforma, facilitar pagos elegibles, verificar activaciones, moderar contenido, prevenir fraude, enviar notificaciones solicitadas y personalizar el descubrimiento."] },
    { title: "3. Intercambio de datos", paragraphs: ["Compartimos información limitada con las marcas, anfitriones, creadores y comercios involucrados en los Momentos a los que te unes, y con proveedores que ayudan a operar Promorang. No vendemos datos personales."] },
    { title: "4. Seguridad", paragraphs: ["Aplicamos medidas de seguridad estándar del sector, aunque ningún método de transmisión por internet es completamente seguro."] },
    { title: "5. Tus derechos", paragraphs: ["Puedes consultar o corregir tu perfil desde la configuración y solicitar la eliminación desde la aplicación o la página de eliminación de cuenta. El contenido compartido se incluye salvo que la ley exija conservarlo."] },
    { title: "6. Conservación", paragraphs: ["Conservamos datos personales solo durante el tiempo necesario. Determinados registros de transacciones, pagos, impuestos, fraude, disputas o regulación podrán conservarse cuando la ley lo exija o para proteger la plataforma y sus usuarios."] },
    { title: "7. Contacto", paragraphs: ["Las preguntas y solicitudes de privacidad pueden enviarse a support@promorang.co."] },
  ] },
  "pt-BR": { title: "Política de Privacidade", seo: "Como tratamos seus dados e protegemos sua privacidade.", updated: "Última atualização: 14 de julho de 2026", sections: [
    { title: "1. Informações que coletamos", paragraphs: ["Coletamos informações fornecidas diretamente, como nome, e-mail, dados do perfil, solicitações de suporte, conteúdo e fotos de comprovação. Também processamos dados de participação, transações, dispositivos, notificações e localização aproximada ou informada quando necessário para operar e verificar Momentos."] },
    { title: "2. Como usamos as informações", paragraphs: ["Usamos as informações para autenticar contas, operar e proteger a plataforma, viabilizar pagamentos elegíveis, verificar ativações, moderar conteúdo, prevenir fraudes, enviar notificações solicitadas e personalizar a descoberta."] },
    { title: "3. Compartilhamento de dados", paragraphs: ["Compartilhamos informações limitadas com marcas, anfitriões, criadores e comerciantes envolvidos nos Momentos dos quais você participa, e com provedores que ajudam a operar a Promorang. Não vendemos dados pessoais."] },
    { title: "4. Segurança", paragraphs: ["Adotamos medidas de segurança padrão do setor, embora nenhum método de transmissão pela internet seja completamente seguro."] },
    { title: "5. Seus direitos", paragraphs: ["Você pode acessar ou corrigir seu perfil nas configurações e solicitar exclusão pelo aplicativo ou pela página de exclusão de conta. Conteúdo compartilhado é incluído, salvo quando a retenção for exigida por lei."] },
    { title: "6. Retenção", paragraphs: ["Mantemos dados pessoais apenas pelo tempo necessário. Certos registros de transações, pagamentos, impostos, prevenção a fraudes, disputas ou regulação podem ser mantidos quando exigido por lei ou para proteger a plataforma e seus usuários."] },
    { title: "7. Contato", paragraphs: ["Perguntas e solicitações de privacidade podem ser enviadas para support@promorang.co."] },
  ] },
};

export const termsContent: Record<Locale, LegalDocument> = {
  en: { title: "Terms of Service", seo: "Terms and conditions for using the Promorang platform.", updated: "Last updated: July 1, 2026", sections: [
    { title: "1. Acceptance of Terms", paragraphs: ["By accessing and using Promorang, you agree to these Terms of Service. If you do not agree, do not use our services."] },
    { title: "2. Description of Service", paragraphs: ["Promorang connects brands, merchants, creators, hosts, and communities for brand-funded activations called Moments."] },
    { title: "3. User Accounts", paragraphs: ["Users must provide accurate information and are responsible for maintaining the security of their account credentials."] },
    { title: "4. Bounties and Payments", paragraphs: ["Bounties are paid after successful verification of required activation proof. Promorang may withhold payments when proof is fraudulent or non-compliant."] },
    { id: "conduct", title: "5. Conduct and User-Generated Content", paragraphs: ["Users must behave professionally and respectfully. Harassment, threats, hate, sexual exploitation, fraud, spam, intellectual-property violations, and dangerous or illegal activity are prohibited.", "By uploading content, you confirm your right to share it and grant Promorang the rights needed to host, display, review, and distribute it within the service. Promorang may restrict or remove content and suspend accounts that violate these rules."] },
    { title: "6. Pioneer Points", paragraphs: ["Pioneer Points are a non-cash record of eligible, verified contribution during a defined Promorang season.", "They cannot be purchased, sold, transferred, withdrawn, or exchanged and are not money, Gems, equity, securities, cryptocurrency, ownership, or a promise of payment. Until a funded reward pool and its terms are published, Pioneer Points have no cash value."] },
    { title: "7. Program Changes", paragraphs: ["Promorang may pause or amend prospective earning rules to protect program integrity. Snapshot records remain subject to verification, fraud review, legal requirements, and correction of technical errors."] },
  ] },
  "es-419": { title: "Términos de Servicio", seo: "Términos y condiciones para usar la plataforma Promorang.", updated: "Última actualización: 1 de julio de 2026", sections: [
    { title: "1. Aceptación de los términos", paragraphs: ["Al acceder y usar Promorang, aceptas estos Términos de Servicio. Si no estás de acuerdo, no uses nuestros servicios."] },
    { title: "2. Descripción del servicio", paragraphs: ["Promorang conecta marcas, comercios, creadores, anfitriones y comunidades para activaciones financiadas por marcas llamadas Momentos."] },
    { title: "3. Cuentas de usuario", paragraphs: ["Los usuarios deben proporcionar información correcta y son responsables de proteger las credenciales de su cuenta."] },
    { title: "4. Recompensas y pagos", paragraphs: ["Las recompensas se pagan tras verificar correctamente las pruebas exigidas. Promorang puede retener pagos cuando las pruebas sean fraudulentas o incumplan las condiciones."] },
    { id: "conduct", title: "5. Conducta y contenido generado por usuarios", paragraphs: ["Los usuarios deben actuar con profesionalidad y respeto. Se prohíben el acoso, las amenazas, el odio, la explotación sexual, el fraude, el spam, las infracciones de propiedad intelectual y las actividades peligrosas o ilegales.", "Al subir contenido, confirmas que puedes compartirlo y otorgas a Promorang los derechos necesarios para alojarlo, mostrarlo, revisarlo y distribuirlo dentro del servicio. Promorang puede restringir o eliminar contenido y suspender cuentas que incumplan estas reglas."] },
    { title: "6. Pioneer Points", paragraphs: ["Los Pioneer Points son un registro no monetario de contribuciones elegibles y verificadas durante una temporada definida.", "No pueden comprarse, venderse, transferirse, retirarse ni cambiarse; no son dinero, Gems, acciones, valores, criptomonedas, propiedad ni una promesa de pago. Hasta que se publique un fondo financiado y sus condiciones, no tienen valor en efectivo."] },
    { title: "7. Cambios del programa", paragraphs: ["Promorang puede pausar o modificar reglas futuras para proteger la integridad del programa. Los registros quedan sujetos a verificación, revisión de fraude, requisitos legales y corrección de errores técnicos."] },
  ] },
  "pt-BR": { title: "Termos de Serviço", seo: "Termos e condições para usar a plataforma Promorang.", updated: "Última atualização: 1º de julho de 2026", sections: [
    { title: "1. Aceitação dos termos", paragraphs: ["Ao acessar e usar a Promorang, você aceita estes Termos de Serviço. Se não concordar, não use nossos serviços."] },
    { title: "2. Descrição do serviço", paragraphs: ["A Promorang conecta marcas, comerciantes, criadores, anfitriões e comunidades para ativações financiadas por marcas chamadas Momentos."] },
    { title: "3. Contas de usuário", paragraphs: ["Os usuários devem fornecer informações corretas e são responsáveis por proteger as credenciais da conta."] },
    { title: "4. Recompensas e pagamentos", paragraphs: ["Recompensas são pagas após a verificação das comprovações exigidas. A Promorang pode reter pagamentos quando a comprovação for fraudulenta ou não estiver em conformidade."] },
    { id: "conduct", title: "5. Conduta e conteúdo gerado por usuários", paragraphs: ["Os usuários devem agir com profissionalismo e respeito. São proibidos assédio, ameaças, ódio, exploração sexual, fraude, spam, violações de propriedade intelectual e atividades perigosas ou ilegais.", "Ao enviar conteúdo, você confirma que pode compartilhá-lo e concede à Promorang os direitos necessários para hospedá-lo, exibi-lo, analisá-lo e distribuí-lo no serviço. A Promorang pode restringir ou remover conteúdo e suspender contas que violem estas regras."] },
    { title: "6. Pioneer Points", paragraphs: ["Pioneer Points são um registro não monetário de contribuições elegíveis e comprovadas durante uma temporada definida.", "Eles não podem ser comprados, vendidos, transferidos, sacados ou trocados e não são dinheiro, Gems, participação societária, valores mobiliários, criptomoeda, propriedade ou promessa de pagamento. Até a publicação de um fundo financiado e seus termos, não possuem valor em dinheiro."] },
    { title: "7. Alterações do programa", paragraphs: ["A Promorang pode pausar ou alterar regras futuras para proteger a integridade do programa. Os registros permanecem sujeitos a verificação, análise de fraude, requisitos legais e correção de erros técnicos."] },
  ] },
};
