import { useState, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Check, CircleAlert, ClipboardPlus, Contact, DollarSign, FormInput, ListChecks, Plus, Settings2, Target } from 'lucide-react';
import { Link } from 'react-router-dom';
import SEO from '@/components/SEO';
import { useCommunityEngine, useCommunityEngineAction } from '@/hooks/useCommunity';
import { CommunityShell, Waiting } from './CommunityPortal';
import { buttonClass, Field, inputClass, secondaryClass } from '@/components/community/CommunityForms';
import { dateLabel } from '@/components/community/CommunitySections';
import type { CommunityEngineContact, CommunityEngineStage, CommunityEngineTask } from '@/types/community';

function EngineFrame({ children }: { children: ReactNode }) {
  return <CommunityShell>
    <SEO title="Business Engine" description="Promorang's first-party customer, pipeline, and follow-up workspace." noindex />
    <header className="border-b border-white/10 bg-[#0D0D0E]/95">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 sm:px-8">
        <Link to="/community" className="inline-flex min-h-11 items-center gap-2 text-sm text-white/75"><ArrowLeft className="h-4 w-4" /> Community</Link>
        <span className="flex items-center gap-2 text-sm font-bold"><BriefcaseBusiness className="h-5 w-5 text-orange-300" /> Business Engine</span>
      </div>
    </header>
    <main id="community-content" className="mx-auto max-w-7xl space-y-8 px-5 pb-20 pt-8 sm:px-8 sm:pt-12">{children}</main>
  </CommunityShell>;
}

function Panel({ title, kicker, children, icon: Icon }: { title: string; kicker?: string; children: ReactNode; icon?: typeof Contact }) {
  return <section className="rounded-[1.5rem] border border-white/15 bg-white/[.025] p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex-1">{kicker && <p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">{kicker}</p>}<h2 className="mt-1 font-serif text-2xl font-bold">{title}</h2></div>{Icon && <Icon className="h-5 w-5 shrink-0 text-orange-300" />}</div>{children}</section>;
}

function isoFromDateTime(value: FormDataEntryValue | undefined) {
  const raw = String(value || '').trim();
  return raw ? new Date(raw).toISOString() : null;
}

function dollars(value: number) { return `$${(Number(value || 0) / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default function CommunityEngine() {
  const query = useCommunityEngine();
  const mutation = useCommunityEngineAction();
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');

  if (query.isLoading) return <Waiting title="Opening your Business Engine…"><p role="status">Loading your workspace, contacts, pipeline, and follow-up list.</p></Waiting>;
  if (query.isError || !query.data) return <Waiting title="The Business Engine is for community members."><p role="alert">{query.error instanceof Error ? query.error.message : 'Join the community first to open a workspace.'}</p><Link to="/community" className={buttonClass}>Back to community <ArrowRight className="h-4 w-4" /></Link></Waiting>;
  const data = query.data;

  async function run(action: string, payload: Record<string, unknown>, success: string): Promise<boolean> {
    setError(''); setNotice('');
    try { await mutation.mutateAsync({ action, data: payload }); setNotice(success); await query.refetch(); return true; }
    catch (err) { setError(err instanceof Error ? err.message : 'That Engine action could not be saved.'); return false; }
  }

  async function openWorkspace(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget));
    await run('engine_open', { name: values.name, plan_key: values.plan_key }, 'Your Business Engine workspace is ready.');
  }
  async function addContact(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form));
    if (await run('engine_contact', { display_name: values.display_name, email: values.email || null, phone: values.phone || null, organization: values.organization || null, source: values.source || 'manual', lifecycle_stage: values.lifecycle_stage || 'new', consent_status: values.consent_status || 'unknown', next_action_at: isoFromDateTime(values.next_action_at), notes: values.notes || null }, 'Contact added to your workspace.')) form.reset();
  }
  async function addDeal(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form));
    if (await run('engine_deal', { stage_id: values.stage_id, title: values.title, contact_id: values.contact_id || null, value_cents: Math.round(Number(values.value || 0) * 100), source: values.source || 'manual', expected_close_at: values.expected_close_at || null, notes: values.notes || null }, 'Pipeline item added.')) form.reset();
  }
  async function addTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form));
    if (await run('engine_task', { title: values.title, contact_id: values.contact_id || null, deal_id: values.deal_id || null, priority: values.priority || 'normal', due_at: isoFromDateTime(values.due_at) }, 'Follow-up task added.')) form.reset();
  }
  async function addAutomation(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget));
    let config: Record<string, unknown> = {};
    try { config = values.config ? JSON.parse(String(values.config)) as Record<string, unknown> : {}; }
    catch { setError('Automation config must be valid JSON.'); return; }
    const form = event.currentTarget;
    if (await run('engine_automation', { name: values.name, trigger_key: values.trigger_key, action_key: values.action_key, status: values.status || 'draft', config }, 'Automation saved as a draft.')) form.reset();
  }
  async function addForm(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget));
    const fields = String(values.fields || '').split(',').map(label => label.trim()).filter(Boolean).slice(0, 50).map(label => ({ key: label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, ''), label, type: 'text' }));
    const form = event.currentTarget;
    if (await run('engine_form', { name: values.name, slug: values.slug, status: values.status || 'draft', fields }, 'Form saved.')) form.reset();
  }

  if (!data.workspace) return <EngineFrame><section className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-[radial-gradient(circle_at_88%_0%,rgba(255,101,0,.2),transparent_42%)] p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-200">First-party tools · builder access</p><h1 className="mt-3 max-w-3xl font-serif text-4xl font-bold leading-tight sm:text-6xl">A simple engine for<br /><span className="text-orange-300">useful follow-through.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">Keep contacts, conversations, offers, and next actions in the same place as your community work. This is the foundation for Promorang-owned CRM and campaign tooling; it does not replace the General Room.</p></section>{notice && <p role="status" className="rounded-xl border border-emerald-300/25 bg-emerald-400/5 p-4 text-sm text-emerald-100">{notice}</p>}{error && <p role="alert" className="rounded-xl border border-red-300/25 bg-red-400/5 p-4 text-sm text-red-100">{error}</p>}{!data.enabled && <Panel title="The pilot is paused" icon={CircleAlert}><p className="mt-3 text-sm leading-7 text-white/65">A platform administrator has paused new Business Engine workspaces. Your General Room access remains independent.</p></Panel>}{data.enabled && data.canCreate ? <Panel title="Open your workspace" kicker="Start small" icon={BriefcaseBusiness}><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Choose a name and a builder lane. You can keep the workspace focused on one offer or customer journey while the pilot is being shaped.</p><form className="mt-6 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end" onSubmit={openWorkspace}><Field label="Workspace name"><input name="name" required minLength={3} maxLength={120} defaultValue="My Promorang workspace" className={inputClass} /></Field><Field label="Lane"><select name="plan_key" className={inputClass} defaultValue="builder"><option value="builder">Business Builder pilot</option><option value="studio">Business Studio pilot</option></select></Field><button disabled={mutation.isPending} className={buttonClass}>{mutation.isPending ? 'Opening…' : 'Open workspace'}<ArrowRight className="h-4 w-4" /></button></form></Panel> : <Panel title="Builder access comes after qualification" icon={Target}><p className="mt-3 text-sm leading-7 text-white/65">The Business Engine is reserved for approved Business Builders. You can keep using the General Room and record interest in the optional track.</p><Link to="/community/network" className={`${buttonClass} mt-5`}>View the Builder track <ArrowRight className="h-4 w-4" /></Link></Panel>}<Link to="/community" className="inline-flex min-h-11 items-center gap-2 text-sm text-orange-200">Return to your community place <ArrowRight className="h-4 w-4" /></Link></EngineFrame>;

  const workspace = data.workspace;
  const openTasks = data.tasks.filter(task => task.status !== 'complete');
  const dealsByStage = (stage: CommunityEngineStage) => data.deals.filter(deal => deal.stage_id === stage.id);
  return <EngineFrame><section className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-[radial-gradient(circle_at_88%_0%,rgba(255,101,0,.2),transparent_42%)] p-6 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-200">Business Engine · {workspace.status}</p><h1 className="mt-3 max-w-3xl font-serif text-4xl font-bold leading-tight sm:text-6xl">{workspace.name}<br /><span className="text-orange-300">Keep the next step visible.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">Contacts, pipeline, follow-up, lightweight automations, and forms in one Promorang-owned workspace.</p></div><div className="rounded-2xl border border-white/15 bg-black/20 px-5 py-4 text-right"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/55">Workspace</p><p className="mt-1 text-sm font-semibold capitalize text-orange-100">{workspace.plan_key} · {workspace.timezone}</p></div></div></section>{notice && <p role="status" className="rounded-xl border border-emerald-300/25 bg-emerald-400/5 p-4 text-sm text-emerald-100">{notice}</p>}{error && <p role="alert" className="rounded-xl border border-red-300/25 bg-red-400/5 p-4 text-sm text-red-100">{error}</p>}{!data.enabled && <p className="rounded-xl border border-amber-300/25 bg-amber-300/[.05] p-4 text-sm leading-6 text-amber-100">The pilot is paused for new workspaces. Your existing records remain visible while the team reviews the next release.</p>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl border border-white/10 p-4"><Contact className="h-5 w-5 text-orange-300" /><p className="mt-5 text-3xl font-black">{data.contacts.length}</p><p className="mt-1 text-xs text-white/55">Contacts</p></article><article className="rounded-2xl border border-white/10 p-4"><DollarSign className="h-5 w-5 text-orange-300" /><p className="mt-5 text-3xl font-black">{data.deals.length}</p><p className="mt-1 text-xs text-white/55">Pipeline items</p></article><article className="rounded-2xl border border-white/10 p-4"><ListChecks className="h-5 w-5 text-orange-300" /><p className="mt-5 text-3xl font-black">{openTasks.length}</p><p className="mt-1 text-xs text-white/55">Open follow-ups</p></article><article className="rounded-2xl border border-white/10 p-4"><FormInput className="h-5 w-5 text-orange-300" /><p className="mt-5 text-3xl font-black">{data.forms.length}</p><p className="mt-1 text-xs text-white/55">Forms</p></article></section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><Panel title="Add a contact" kicker="People first" icon={Contact}><form className="mt-5 space-y-4" onSubmit={addContact}><Field label="Name"><input name="display_name" required minLength={2} maxLength={160} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Email"><input name="email" type="email" className={inputClass} /></Field><Field label="Phone"><input name="phone" maxLength={40} className={inputClass} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Organization"><input name="organization" maxLength={160} className={inputClass} /></Field><Field label="Lifecycle"><select name="lifecycle_stage" className={inputClass}><option value="new">New</option><option value="qualified">Qualified</option><option value="active">Active</option><option value="customer">Customer</option></select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Consent"><select name="consent_status" className={inputClass}><option value="unknown">Unknown</option><option value="operational">Operational</option><option value="marketing">Marketing</option></select></Field><Field label="Next action"><input name="next_action_at" type="datetime-local" className={inputClass} /></Field></div><Field label="Notes"><textarea name="notes" rows={2} maxLength={4000} className={inputClass} /></Field><button disabled={mutation.isPending || workspace.status === 'paused'} className={buttonClass}>{mutation.isPending ? 'Saving…' : 'Add contact'}<Plus className="h-4 w-4" /></button></form></Panel>
      <Panel title="Create a follow-up" kicker="Make it actionable" icon={ClipboardPlus}><form className="mt-5 space-y-4" onSubmit={addTask}><Field label="What needs doing?"><input name="title" required minLength={2} maxLength={240} className={inputClass} placeholder="Send the proposal and ask for a decision" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Priority"><select name="priority" className={inputClass}><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></Field><Field label="Due"><input name="due_at" type="datetime-local" className={inputClass} /></Field></div><Field label="Related contact · optional"><select name="contact_id" className={inputClass}><option value="">No contact selected</option>{data.contacts.map(contact => <option key={contact.id} value={contact.id}>{contact.display_name}</option>)}</select></Field><Field label="Related pipeline item · optional"><select name="deal_id" className={inputClass}><option value="">No deal selected</option>{data.deals.map(deal => <option key={deal.id} value={deal.id}>{deal.title}</option>)}</select></Field><button disabled={mutation.isPending || workspace.status === 'paused'} className={buttonClass}>{mutation.isPending ? 'Saving…' : 'Add follow-up'}<Plus className="h-4 w-4" /></button></form></Panel></section>
    <Panel title="Pipeline" kicker="Move conversations forward" icon={Target}><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-6">{data.stages.map(stage => <div key={stage.id} className="min-h-40 rounded-2xl border border-white/10 bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">{stage.name}</h3><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] text-white/60">{dealsByStage(stage).length}</span></div><div className="mt-3 space-y-2">{dealsByStage(stage).map(deal => <article key={deal.id} className="rounded-xl border border-white/10 bg-white/[.04] p-3"><p className="text-sm font-semibold">{deal.title}</p><p className="mt-1 text-xs text-orange-200">{dollars(deal.value_cents)}</p>{deal.contact?.display_name && <p className="mt-1 text-xs text-white/55">{deal.contact.display_name}</p>}</article>)}{!dealsByStage(stage).length && <p className="py-4 text-center text-xs text-white/40">Empty</p>}</div></div>)}</div><form className="mt-7 grid gap-4 border-t border-white/10 pt-5 md:grid-cols-2 xl:grid-cols-4" onSubmit={addDeal}><Field label="Pipeline item"><input name="title" required minLength={2} maxLength={160} className={inputClass} placeholder="Brand intro call" /></Field><Field label="Stage"><select name="stage_id" className={inputClass} required>{data.stages.map(stage => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></Field><Field label="Value · USD"><input name="value" type="number" min={0} step="0.01" defaultValue="0" className={inputClass} /></Field><Field label="Contact · optional"><select name="contact_id" className={inputClass}><option value="">No contact selected</option>{data.contacts.map(contact => <option key={contact.id} value={contact.id}>{contact.display_name}</option>)}</select></Field><Field label="Expected close"><input name="expected_close_at" type="date" className={inputClass} /></Field><Field label="Source"><input name="source" maxLength={80} defaultValue="manual" className={inputClass} /></Field><Field label="Notes"><input name="notes" maxLength={4000} className={inputClass} /></Field><button disabled={mutation.isPending || workspace.status === 'paused'} className={`${buttonClass} self-end`}>{mutation.isPending ? 'Saving…' : 'Add to pipeline'}<Plus className="h-4 w-4" /></button></form></Panel>
    <section className="grid gap-6 xl:grid-cols-2"><Panel title="Follow-up queue" kicker="Do the next useful thing" icon={ListChecks}><div className="mt-5 divide-y divide-white/10">{openTasks.map(task => <TaskRow key={task.id} task={task} disabled={mutation.isPending || workspace.status === 'paused'} onComplete={() => void run('engine_task_complete', { id: task.id }, 'Task marked complete.')} />)}{!openTasks.length && <p className="py-5 text-sm text-white/60">No open follow-ups. Add one when a conversation needs a next step.</p>}</div></Panel><Panel title="Contacts" kicker="Your working list" icon={Contact}><div className="mt-5 divide-y divide-white/10">{data.contacts.slice(0, 12).map(contact => <ContactRow key={contact.id} contact={contact} />)}{!data.contacts.length && <p className="py-5 text-sm text-white/60">Your first contact can be someone you already serve or want to help.</p>}</div></Panel></section>
    <section className="grid gap-6 xl:grid-cols-2"><Panel title="Lightweight automation" kicker="Keep the promise" icon={Settings2}><form className="mt-5 space-y-4" onSubmit={addAutomation}><Field label="Automation name"><input name="name" required minLength={3} maxLength={160} className={inputClass} placeholder="New lead follow-up" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="When"><input name="trigger_key" required minLength={2} maxLength={80} defaultValue="contact.created" className={inputClass} /></Field><Field label="Do"><input name="action_key" required minLength={2} maxLength={80} defaultValue="task.create" className={inputClass} /></Field></div><Field label="Config · JSON"><textarea name="config" rows={2} className={inputClass} placeholder='{"delay_hours": 24}' /></Field><button disabled={mutation.isPending || workspace.status === 'paused'} className={secondaryClass}>{mutation.isPending ? 'Saving…' : 'Save automation draft'}<Settings2 className="h-4 w-4" /></button></form><div className="mt-5 divide-y divide-white/10">{data.automations.map(automation => <div key={automation.id} className="py-3 text-sm"><div className="flex justify-between gap-3"><span className="font-semibold">{automation.name}</span><span className="capitalize text-orange-200">{automation.status}</span></div><p className="mt-1 text-xs text-white/55">{automation.trigger_key} → {automation.action_key}</p></div>)}</div></Panel><Panel title="Forms" kicker="Capture demand with consent" icon={FormInput}><form className="mt-5 space-y-4" onSubmit={addForm}><Field label="Form name"><input name="name" required minLength={3} maxLength={160} className={inputClass} placeholder="Request a campaign consult" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Slug"><input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={80} className={inputClass} placeholder="campaign-consult" /></Field><Field label="Fields · comma separated"><input name="fields" maxLength={2000} className={inputClass} placeholder="Name, Email, What do you need?" /></Field></div><button disabled={mutation.isPending || workspace.status === 'paused'} className={secondaryClass}>{mutation.isPending ? 'Saving…' : 'Save form'}<FormInput className="h-4 w-4" /></button></form><div className="mt-5 divide-y divide-white/10">{data.forms.map(form => <div key={form.id} className="py-3 text-sm"><div className="flex justify-between gap-3"><span className="font-semibold">/{form.slug}</span><span className="capitalize text-orange-200">{form.status}</span></div><p className="mt-1 text-xs text-white/55">{form.name} · {form.submission_count} submissions</p></div>)}</div></Panel></section>
    <section className="rounded-2xl border border-amber-300/25 bg-amber-300/[.05] p-5 text-sm leading-7 text-amber-100"><strong>Keep this tool honest.</strong> Only contact people with an appropriate consent basis, make opt-out paths clear, and treat pipeline value as a forecast rather than earned revenue. <Link to="/community/network" className="font-semibold underline">Read the Builder track guardrails.</Link></section>
  </EngineFrame>;
}

function TaskRow({ task, disabled, onComplete }: { task: CommunityEngineTask; disabled: boolean; onComplete: () => void }) {
  return <div className="flex items-start justify-between gap-3 py-3"><div><p className="text-sm font-semibold">{task.title}</p><p className="mt-1 text-xs text-white/55"><span className="capitalize">{task.priority}</span>{task.due_at ? ` · due ${dateLabel(task.due_at, true)}` : ''}</p></div><button type="button" disabled={disabled} onClick={onComplete} aria-label={`Complete ${task.title}`} className="inline-flex min-h-9 items-center gap-2 rounded-full border border-white/20 px-3 text-xs text-white/70 hover:bg-white/10 disabled:opacity-50"><Check className="h-3.5 w-3.5" /> Done</button></div>;
}

function ContactRow({ contact }: { contact: CommunityEngineContact }) {
  return <div className="flex items-start justify-between gap-3 py-3"><div><p className="text-sm font-semibold">{contact.display_name}</p><p className="mt-1 text-xs text-white/55">{contact.organization || contact.email || 'No organization or email'} · <span className="capitalize">{contact.lifecycle_stage}</span></p></div><span className="text-xs capitalize text-orange-200">{contact.consent_status}</span></div>;
}
