import { useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, CheckCircle2, ClipboardList, Gauge, Network, RefreshCw, ShieldCheck, SlidersHorizontal, Users, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import SEO from '@/components/SEO';
import { useCommunityAdmin, useCommunityAdminAction } from '@/hooks/useCommunity';
import { CommunityShell, Waiting } from './CommunityPortal';
import { buttonClass, inputClass, secondaryClass } from '@/components/community/CommunityForms';
import { dateLabel, human } from '@/components/community/CommunitySections';
import type { CommunityAdminData, CommunityMembership, CommunityNetworkEnrollment, CommunityNetworkEvent } from '@/types/community';

type AdminTab = 'overview' | 'members' | 'work' | 'network' | 'engine' | 'audit';

function AdminButton({ action, data, children, secondary = true, onDone }: { action: string; data: Record<string, unknown>; children: ReactNode; secondary?: boolean; onDone: (message: string) => void }) {
  const mutation = useCommunityAdminAction();
  return <div>
    <button className={secondary ? secondaryClass : buttonClass} disabled={mutation.isPending} onClick={async () => {
      try { await mutation.mutateAsync({ action, data }); onDone('Saved. The control room is up to date.'); }
      catch (error) { onDone(error instanceof Error ? error.message : 'That admin action could not be saved.'); }
    }}>{mutation.isPending ? 'Saving…' : children}</button>
  </div>;
}

const metricCards = [
  ['activeMembers', 'Active members', Users], ['pendingMembers', 'Needs review', ClipboardList], ['submittedWork', 'Work waiting', CheckCircle2],
  ['heldGems', 'Gems held', WalletCards], ['builders', 'Business Builders', BriefcaseBusiness], ['activeNetworkMembers', 'Network pilot', Network],
] as const;

function MemberRow({ member, onDone }: { member: CommunityMembership; onDone: (message: string) => void }) {
  const [kind, setKind] = useState<'participant' | 'builder'>(member.member_kind || 'participant');
  const [tier, setTier] = useState(member.tier);
  const [status, setStatus] = useState(member.status);
  return <article className="rounded-2xl border border-white/10 bg-white/[.025] p-4">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold">{member.display_name}</h3><p className="mt-1 text-xs text-white/55">{member.career_path} · joined {dateLabel(member.joined_at)}</p><p className="mt-2 max-w-xl text-sm leading-6 text-white/70">{member.personal_goal}</p></div><div className="flex flex-wrap gap-2 text-[10px] font-bold uppercase tracking-wider"><span className="rounded-full border border-white/15 px-2.5 py-1">{member.status}</span><span className="rounded-full border border-orange-300/30 px-2.5 py-1 text-orange-200">{member.member_kind || 'participant'}</span>{member.can_manage && <span className="rounded-full bg-orange-300 px-2.5 py-1 text-black">lead</span>}</div></div>
    <div className="mt-4 flex flex-wrap items-end gap-3 border-t border-white/10 pt-4"><label className="text-xs text-white/60">Access<select className={inputClass} value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="pending">Pending</option><option value="active">Active</option><option value="paused">Paused</option><option value="removed">Removed</option></select></label><label className="text-xs text-white/60">Place<select className={inputClass} value={kind} onChange={e => setKind(e.target.value as typeof kind)}><option value="participant">Participant</option><option value="builder">Business Builder</option></select></label><label className="text-xs text-white/60">Tier<select className={inputClass} value={tier} onChange={e => setTier(e.target.value as typeof tier)}><option value="free">Free</option><option value="premium">Premium</option><option value="super">Super</option></select></label><AdminButton action="admin_membership" data={{ id: member.id, status, tier, member_kind: kind }} onDone={onDone}>Save membership</AdminButton><AdminButton action="admin_lead_access" data={{ id: member.id, can_manage: !member.can_manage }} onDone={onDone}>{member.can_manage ? 'Remove lead access' : 'Grant lead access'}</AdminButton></div>
  </article>;
}

function NetworkRow({ enrollment, onDone }: { enrollment: CommunityNetworkEnrollment; onDone: (message: string) => void }) {
  const [status, setStatus] = useState(enrollment.status);
  const [plan, setPlan] = useState(enrollment.plan_key);
  return <article className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold">{enrollment.user_id.slice(0, 8)}…</h3><p className="mt-1 text-xs text-white/55">{enrollment.sponsor_user_id ? `Sponsor ${enrollment.sponsor_user_id.slice(0, 8)}… · ` : ''}{dateLabel(enrollment.joined_at)}</p></div><span className="rounded-full border border-orange-300/30 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-orange-200">{human(enrollment.status)}</span></div><div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-xs text-white/60">Review<select className={inputClass} value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="interest">Interest</option><option value="pending">Pending</option><option value="active">Active</option><option value="paused">Paused</option><option value="withdrawn">Withdrawn</option></select></label><label className="text-xs text-white/60">Plan<select className={inputClass} value={plan} onChange={e => setPlan(e.target.value as typeof plan)}><option value="builder">Builder</option><option value="studio">Studio</option></select></label><AdminButton action="admin_network_enrollment" data={{ id: enrollment.id, status, plan_key: plan }} onDone={onDone}>Update pilot</AdminButton></div></article>;
}

function EventRow({ event, onDone }: { event: CommunityNetworkEvent; onDone: (message: string) => void }) {
  const [status, setStatus] = useState<'verified' | 'rejected' | 'void'>(event.status === 'verified' ? 'verified' : event.status === 'rejected' ? 'rejected' : 'verified');
  const [notes, setNotes] = useState(event.notes || '');
  return <article className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold">{human(event.event_type)}</h3><p className="mt-1 text-xs text-white/55">{event.enrollment?.user_id ? `${event.enrollment.user_id.slice(0, 8)}… · ` : ''}{event.source_ref || 'No source reference'} · {dateLabel(event.created_at, true)}</p></div><span className="rounded-full border border-orange-300/30 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-orange-200">{human(event.status)} · ${(event.value_cents / 100).toFixed(2)}</span></div><div className="mt-4 flex flex-wrap items-end gap-3 border-t border-white/10 pt-4"><label className="text-xs text-white/60">Decision<select className={inputClass} value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="verified">Verify</option><option value="rejected">Reject</option><option value="void">Void</option></select></label><label className="min-w-[16rem] flex-1 text-xs text-white/60">Review note<input className={inputClass} value={notes} onChange={e => setNotes(e.target.value)} minLength={3} maxLength={2000} placeholder="What evidence did you check?" /></label><AdminButton action="admin_verify_event" data={{ id: event.id, status, notes: notes.trim() || 'Reviewed by platform administrator.' }} onDone={onDone}>Save review</AdminButton></div></article>;
}

function SettingsPanel({ data, onDone }: { data: CommunityAdminData; onDone: (message: string) => void }) {
  const settings = data.settings;
  const mutation = useCommunityAdminAction();
  const [error, setError] = useState('');
  async function save(next: Record<string, unknown>) {
    setError('');
    try {
      await mutation.mutateAsync({ action: 'admin_network_settings', data: next });
      onDone('Program settings saved.');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Program settings could not be saved.');
    }
  }
  return <section className="rounded-[1.5rem] border border-white/15 bg-white/[.025] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Operating posture</p><h2 className="mt-2 font-serif text-3xl font-bold">Choose what is open.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">Participant access, the optional network pilot, and the first-party Business Engine are independent switches. Turning on the pilot does not publish a compensation plan or create an income promise.</p></div><SlidersHorizontal className="h-6 w-6 shrink-0 text-orange-300" /></div><div className="mt-6 grid gap-3 md:grid-cols-3">
    {([['participant_access_enabled', 'General community', 'People can join as participants and use the shared community layer.'], ['matrix_program_enabled', 'Builder pilot', 'Members can record interest in the product-led network track.'], ['business_engine_enabled', 'Business Engine', 'Approved builders can open a first-party CRM workspace.']] as const).map(([key, title, detail]) => <div key={key} className="rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs leading-5 text-white/55">{detail}</p></div><button type="button" aria-pressed={Boolean(settings[key])} disabled={mutation.isPending} onClick={() => void save({ ...settings, [key]: !settings[key] })} className={`h-8 w-14 rounded-full p-1 transition ${settings[key] ? 'bg-orange-300' : 'bg-white/15'} disabled:opacity-50`}><span className={`block h-6 w-6 rounded-full bg-black transition ${settings[key] ? 'translate-x-6' : ''}`} /></button></div></div>)}
  </div><div className="mt-5 flex flex-wrap items-center gap-3 border-t border-white/10 pt-5"><span className="text-sm text-white/65">Network mode</span>{(['pilot', 'active', 'paused'] as const).map(mode => <button type="button" key={mode} disabled={mutation.isPending} className={settings.matrix_mode === mode ? buttonClass : secondaryClass} onClick={() => void save({ ...settings, matrix_mode: mode })}>{mode === 'pilot' ? 'Pilot' : mode === 'active' ? 'Active' : 'Paused'}</button>)}</div>{error && <p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}</section>;
}

export default function CommunityAdmin() {
  const query = useCommunityAdmin();
  const [tab, setTab] = useState<AdminTab>('overview');
  const [notice, setNotice] = useState('');
  if (query.isLoading) return <Waiting title="Opening the control room…"><p role="status">Checking platform administrator access and loading community operations.</p></Waiting>;
  if (query.isError || !query.data) return <Waiting title="This room is restricted."><p role="alert">{query.error instanceof Error ? query.error.message : 'A platform administrator is required for the community control room.'}</p><Link to="/community" className={buttonClass}>Back to community <ArrowRight className="h-4 w-4" /></Link></Waiting>;
  const data = query.data;
  const metrics = data.metrics;
  const tabs: Array<[AdminTab, string, typeof Gauge]> = [['overview', 'Overview', Gauge], ['members', 'Members', Users], ['work', 'Work & roles', ClipboardList], ['network', 'Network pilot', Network], ['engine', 'Business Engine', BriefcaseBusiness], ['audit', 'Audit', ShieldCheck]];
  return <CommunityShell><SEO title="Community Admin" description="Promorang community operations control room." noindex /><header className="sticky top-0 z-30 border-b border-white/10 bg-[#0D0D0E]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link to="/community" className="inline-flex min-h-11 items-center gap-2 text-sm text-white/75"><ArrowLeft className="h-4 w-4" /> Community</Link><span className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="h-5 w-5 text-orange-300" /> Control room</span></div><nav aria-label="Community admin" className="mx-auto flex max-w-7xl gap-5 overflow-x-auto px-5 sm:px-8">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex min-h-12 shrink-0 items-center gap-2 border-b-2 text-sm font-semibold ${tab === id ? 'border-orange-400 text-orange-200' : 'border-transparent text-white/60 hover:text-white'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav></header><main className="mx-auto max-w-7xl space-y-8 px-5 pb-20 pt-8 sm:px-8 sm:pt-12">{notice && <div role="status" className="flex items-center justify-between gap-3 rounded-xl border border-emerald-300/25 bg-emerald-400/5 p-4 text-sm text-emerald-100"><span>{notice}</span><button className="min-h-8 min-w-8" onClick={() => setNotice('')} aria-label="Dismiss update">×</button></div>}
    <section className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-[radial-gradient(circle_at_88%_0%,rgba(255,101,0,.22),transparent_38%)] p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-200">Promorang Community · platform administration</p><div className="mt-3 flex flex-wrap items-end justify-between gap-6"><div><h1 className="max-w-3xl font-serif text-4xl font-bold leading-tight sm:text-6xl">Keep the room useful,<br /><span className="text-orange-300">fair, and moving.</span></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/65">This is the operating layer behind the member experience: access, roles, work, funding, network policy, and the first-party tools members can grow into.</p></div><div className="rounded-2xl border border-white/15 bg-black/20 px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/55">Refresh cycle</p><p className="mt-1 flex items-center gap-2 text-sm text-orange-100"><RefreshCw className="h-4 w-4" /> Live · 30 seconds</p></div></div></section>
    {(tab === 'overview') && <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metricCards.map(([key, label, Icon]) => <article className="rounded-2xl border border-white/10 bg-white/[.025] p-4" key={key}><Icon className="h-5 w-5 text-orange-300" /><p className="mt-6 text-3xl font-black">{typeof metrics[key] === 'number' ? metrics[key].toLocaleString() : metrics[key]}</p><p className="mt-1 text-xs text-white/55">{label}</p></article>)}</section><SettingsPanel data={data} onDone={message => { setNotice(message); void query.refetch(); }} /><section className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Today’s queues</p><h2 className="mt-2 font-serif text-3xl font-bold">Where attention goes next.</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between border-b border-white/10 pb-3"><span className="text-white/65">Pending member requests</span><strong>{metrics.pendingMembers}</strong></div><div className="flex justify-between border-b border-white/10 pb-3"><span className="text-white/65">Receipts waiting for review</span><strong>{metrics.submittedWork}</strong></div><div className="flex justify-between border-b border-white/10 pb-3"><span className="text-white/65">Network interests to qualify</span><strong>{metrics.networkInterest}</strong></div><div className="flex justify-between"><span className="text-white/65">Open follow-up tasks</span><strong>{metrics.openEngineTasks}</strong></div></div><button className={`${secondaryClass} mt-5`} onClick={() => setTab(metrics.pendingMembers ? 'members' : metrics.submittedWork ? 'work' : 'network')}>Open the next queue <ArrowRight className="h-4 w-4" /></button></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Guardrail</p><h2 className="mt-2 font-serif text-3xl font-bold">Product before network.</h2><p className="mt-4 text-sm leading-7 text-white/65">General participants keep access to community activity without joining the builder track. Builder interest is recorded separately. Any future network reward must follow verified external commerce, published terms, and professional review.</p><div className="mt-5 flex flex-wrap gap-3"><Link to="/community/network" className={secondaryClass}>View member-facing network page <ArrowRight className="h-4 w-4" /></Link><Link to="/community/engine" className={secondaryClass}>Open Business Engine <ArrowRight className="h-4 w-4" /></Link></div></article></section></>}
    {tab === 'members' && <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Access desk</p><h2 className="mt-2 font-serif text-4xl font-bold">Every place has a status.</h2></div><span className="text-sm text-white/60">{data.members.length} records</span></div>{data.members.map(member => <MemberRow key={member.id} member={member} onDone={message => { setNotice(message); void query.refetch(); }} />)}</section>}
    {tab === 'work' && <section className="space-y-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Operations desk</p><h2 className="mt-2 font-serif text-4xl font-bold">Work, roles, and release decisions.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Detailed proof review, funding, goals, and role check-ins remain in the Lead Room. This view keeps the platform administrator aware of the queues and their size.</p><Link to="/community/lead" className={`${buttonClass} mt-5`}>Open Lead Room <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.submittedWork}</p><p className="mt-1 text-xs text-white/55">Receipts waiting</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.openMoves}</p><p className="mt-1 text-xs text-white/55">Open moves</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.activeRoles}</p><p className="mt-1 text-xs text-white/55">Active or grace roles</p></article></div><div className="rounded-2xl border border-white/10 p-5"><h3 className="font-serif text-2xl font-bold">Review queue</h3><div className="mt-4 divide-y divide-white/10">{data.reviewQueue.map(item => <div key={item.id} className="flex flex-wrap justify-between gap-3 py-4 text-sm"><span>{item.move.title}</span><span className="text-white/55">{human(item.status)} · {dateLabel(item.submitted_at, true)}</span></div>)}{!data.reviewQueue.length && <p className="py-6 text-sm text-white/60">Nothing waiting for review.</p>}</div></div></section>}
    {tab === 'network' && <section className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Optional product-led network</p><h2 className="mt-2 font-serif text-4xl font-bold">Interest is not entitlement.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-white/65">Review who wants the Business Builder track, keep participant access independent, and verify external activity before any future reward is considered.</p></div><div className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.networkInterest}</p><p className="mt-1 text-xs text-white/55">Interests awaiting review</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.activeNetworkMembers}</p><p className="mt-1 text-xs text-white/55">Active pilot members</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.verifiedNetworkEvents}</p><p className="mt-1 text-xs text-white/55">Verified activity records</p></article></div><div className="space-y-4">{data.enrollments.map(enrollment => <NetworkRow key={enrollment.id} enrollment={enrollment} onDone={message => { setNotice(message); void query.refetch(); }} />)}{!data.enrollments.length && <p className="rounded-2xl border border-dashed border-white/20 p-8 text-sm text-white/60">No network interest has been recorded.</p>}</div><div><div className="mb-4"><h3 className="font-serif text-2xl font-bold">Activity awaiting verification</h3><p className="mt-1 text-sm text-white/60">Every record needs evidence before a future compensation rule could consider it.</p></div><div className="space-y-4">{data.events.filter(event => event.status === 'pending').map(event => <EventRow key={event.id} event={event} onDone={message => { setNotice(message); void query.refetch(); }} />)}{!data.events.some(event => event.status === 'pending') && <p className="rounded-2xl border border-dashed border-white/20 p-6 text-sm text-white/60">No pending activity records.</p>}</div></div><div className="rounded-2xl border border-amber-300/25 bg-amber-300/[.05] p-5 text-sm leading-7 text-amber-100">Compensation controls are intentionally not automatic here. The pilot stores product participation and verifiable activity first. Legal, tax, consumer-protection, and financial review must happen before publishing a paid plan.</div></section>}
    {tab === 'engine' && <section className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">First-party infrastructure</p><h2 className="mt-2 font-serif text-4xl font-bold">Build the Business Engine in-house.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-white/65">The first slice replaces dependency on a white-labeled third-party CRM with owned contacts, pipeline, follow-up, forms, and automation primitives. Keep the product useful before adding breadth.</p></div><div className="grid gap-4 sm:grid-cols-4"><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.engineWorkspaces}</p><p className="mt-1 text-xs text-white/55">Workspaces</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.engineContacts}</p><p className="mt-1 text-xs text-white/55">Contacts</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.engineDeals}</p><p className="mt-1 text-xs text-white/55">Pipeline items</p></article><article className="rounded-2xl border border-white/10 p-5"><p className="text-3xl font-black">{metrics.openEngineTasks}</p><p className="mt-1 text-xs text-white/55">Open tasks</p></article></div><div className="space-y-3">{data.engineWorkspaces.map(workspace => <article key={workspace.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 p-5"><div><h3 className="font-semibold">{workspace.name}</h3><p className="mt-1 text-xs text-white/55">{workspace.owner_id?.slice(0, 8) || 'owner'}… · {workspace.plan_key} · {workspace.status}</p></div><div className="flex flex-wrap gap-3"><AdminButton action="admin_workspace_status" data={{ id: workspace.id, status: workspace.status === 'paused' ? 'active' : 'paused', plan_key: workspace.plan_key }} onDone={message => { setNotice(message); void query.refetch(); }}>{workspace.status === 'paused' ? 'Resume workspace' : 'Pause workspace'}</AdminButton><Link to="/community/engine" className={secondaryClass}>Open Engine <ArrowRight className="h-4 w-4" /></Link></div></article>)}{!data.engineWorkspaces.length && <p className="rounded-2xl border border-dashed border-white/20 p-8 text-sm text-white/60">No Business Engine workspaces yet.</p>}</div></section>}
    {tab === 'audit' && <section><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Immutable operations trail</p><h2 className="mt-2 font-serif text-4xl font-bold">What changed, and when.</h2></div><div className="mt-6 divide-y divide-white/10 rounded-2xl border border-white/10">{data.audit.map(item => <article key={item.id} className="flex flex-wrap justify-between gap-4 p-4 text-sm"><div><p className="font-semibold">{human(item.action)}</p><p className="mt-1 text-xs text-white/50">Record {item.record_id ? `${item.record_id.slice(0, 8)}…` : '—'} · actor {item.actor_id.slice(0, 8)}…</p></div><time className="text-xs text-white/55">{dateLabel(item.created_at, true)}</time></article>)}{!data.audit.length && <p className="p-8 text-sm text-white/60">No operations recorded yet.</p>}</div></section>}
  </main></CommunityShell>;
}
