import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarCheck, ExternalLink, Loader2, Send, Upload } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useImageUpload } from "@/hooks/useImageUpload";
import { useClaimEventVerification, useEventVerificationMissions } from "@/hooks/useEventVerification";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { useI18n } from "@/i18n/I18nContext";

type Claim={id:string;status:string;mission_type:string;title:string;instructions:string;reward_points:number;event_title:string;expires_at:string;reviewer_notes:string|null;reward_points_awarded:number};
export default function EventScout(){
  const { t } = useI18n();
  const {user}=useAuth();const client=useQueryClient();const missions=useEventVerificationMissions();const claim=useClaimEventVerification();const {uploadImage,uploading}=useImageUpload();
  const [values,setValues]=useState<Record<string,string>>({});const [notes,setNotes]=useState<Record<string,string>>({});const [files,setFiles]=useState<Record<string,File|null>>({});const [busy,setBusy]=useState<string|null>(null);
  const claims=useQuery({queryKey:["my-event-verification-claims",user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await (supabase as any).from("view_my_event_verification_claims").select("*").order("claimed_at",{ascending:false});if(error)throw error;return(data||[]) as Claim[];}});
  const submit=async(item:Claim)=>{if(!user)return;setBusy(item.id);try{const proof:any[]=[];const file=files[item.id];if(file){const url=await uploadImage(file,"enrichment-proofs",user.id);if(!url)throw new Error("Proof upload failed");proof.push({type:"media",url});}const value=values[item.id]?.trim();if(!value&&!proof.length)throw new Error("Add a verified value or proof file");const {error}=await (supabase as any).rpc("submit_event_verification",{p_claim_id:item.id,p_proposed_value:{value:value||null},p_proof:proof,p_notes:notes[item.id]?.trim()||null});if(error)throw error;toast.success("Event evidence submitted for review.");await client.invalidateQueries({queryKey:["my-event-verification-claims"]});}catch(e:any){toast.error(e.message)}finally{setBusy(null)}};
  const active=(claims.data||[]).filter(x=>x.status==="claimed");
  return <main className="mx-auto min-h-screen max-w-6xl px-4 py-12"><p className="text-xs font-black uppercase tracking-[.24em] text-primary">{t("eventScout.badge")}</p><h1 className="mt-3 font-serif text-5xl font-bold">{t("eventScout.title")}</h1><p className="mt-3 max-w-3xl text-muted-foreground">{t("eventScout.subtitle")}</p>
    <section className="mt-10"><h2 className="font-serif text-3xl font-bold">{t("eventScout.openMissions")}</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{missions.isLoading?<Loader2 className="animate-spin"/>:missions.data?.map(m=><article key={m.id} className="rounded-3xl border border-border bg-card p-6"><div className="flex justify-between gap-3"><Badge>{m.mission_type}</Badge><span className="text-sm font-bold text-amber-500">{m.reward_points} pts</span></div><h3 className="mt-4 text-xl font-bold">{m.event_title}</h3><p className="mt-1 text-sm font-semibold text-primary">{m.title}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{m.instructions}</p><div className="mt-5 flex items-center justify-between"><a href={m.source_url||"#"} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-primary">Source <ExternalLink className="h-3 w-3"/></a><Button size="sm" disabled={!user||m.status!=="open"||claim.isPending} onClick={()=>claim.mutate(m.id,{onSuccess:()=>toast.success("Event mission claimed for 48 hours."),onError:(e:any)=>toast.error(e.message)})}>{t("eventScout.claimMission")}</Button></div></article>)}</div></section>
    {active.length?<section className="mt-12"><h2 className="font-serif text-3xl font-bold">{t("eventScout.fieldAssignments")}</h2><div className="mt-4 space-y-4">{active.map(c=><article key={c.id} className="rounded-3xl border border-primary/20 bg-card p-6"><div className="flex justify-between"><div><Badge variant="outline">{c.mission_type}</Badge><h3 className="mt-3 text-2xl font-bold">{c.event_title}</h3><p className="text-sm text-muted-foreground">{c.instructions}</p></div><CalendarCheck className="h-7 w-7 text-primary"/></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Input value={values[c.id]||""} onChange={e=>setValues(v=>({...v,[c.id]:e.target.value}))} placeholder="Confirmed venue, time, URL, organizer or recurrence"/><label className="flex h-10 cursor-pointer items-center justify-center gap-2 rounded-md border"><Upload className="h-4 w-4"/>{files[c.id]?.name||"Attach proof"}<input className="sr-only" type="file" accept="image/*,application/pdf" onChange={e=>setFiles(v=>({...v,[c.id]:e.target.files?.[0]||null}))}/></label><Textarea className="md:col-span-2" value={notes[c.id]||""} onChange={e=>setNotes(v=>({...v,[c.id]:e.target.value}))} placeholder="What did you verify, from where, and when?"/><Button className="md:col-span-2" disabled={busy===c.id||uploading} onClick={()=>submit(c)}>{busy===c.id?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Send className="mr-2 h-4 w-4"/>}{t("eventScout.submitEvidence")}</Button></div></article>)}</div></section>:null}
    {(claims.data||[]).some(x=>x.status!=="claimed")?<section className="mt-12"><h2 className="font-serif text-3xl font-bold">{t("eventScout.history")}</h2><div className="mt-4 space-y-2">{(claims.data||[]).filter(x=>x.status!=="claimed").map(c=><div key={c.id} className="flex justify-between rounded-2xl border p-4"><div><p className="font-bold">{c.event_title}</p><p className="text-sm text-muted-foreground">{c.reviewer_notes||"Awaiting review"}</p></div><Badge>{c.status}{c.reward_points_awarded?` · +${c.reward_points_awarded}`:""}</Badge></div>)}</div></section>:null}
  </main>;
}
