import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Camera, CheckCircle2, Clock3, Compass, Loader2, Send, Upload } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useImageUpload } from "@/hooks/useImageUpload";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { useI18n } from "@/i18n/I18nContext";

type Claim = { id:string; status:string; field_key:string; title:string; instructions:string; proof_requirements:string[]; reward_points:number; venue_name:string; venue_slug:string; city:string; expires_at:string; proposed_value:any; proof:any[]; reviewer_notes:string|null; reward_points_awarded:number; reputation_delta:number };

export default function ScoutEnrichment() {
  const { t } = useI18n();
  const { user } = useAuth(); const queryClient = useQueryClient(); const { uploadImage, uploading } = useImageUpload();
  const [values,setValues]=useState<Record<string,string>>({}); const [notes,setNotes]=useState<Record<string,string>>({}); const [files,setFiles]=useState<Record<string,File|null>>({}); const [busy,setBusy]=useState<string|null>(null);
  const query=useQuery({queryKey:["my-enrichment-claims",user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await (supabase as any).from("view_my_enrichment_claims").select("*").order("claimed_at",{ascending:false});if(error)throw error;return(data||[]) as Claim[]}});
  const groups=useMemo(()=>({active:(query.data||[]).filter(c=>c.status==="claimed"),review:(query.data||[]).filter(c=>c.status==="submitted"),complete:(query.data||[]).filter(c=>["approved","rejected"].includes(c.status))}),[query.data]);
  const submit=async(claim:Claim)=>{if(!user)return;setBusy(claim.id);try{const proof:any[]=[];const file=files[claim.id];if(file){const url=await uploadImage(file,"enrichment-proofs",user.id);if(!url)throw new Error("Proof upload failed");proof.push({type:"media",url,submitted_at:new Date().toISOString()});}const value=values[claim.id]?.trim();if(!value&&!proof.length)throw new Error("Add a value, link, or proof image");const {error}=await (supabase as any).rpc("submit_listing_enrichment",{p_claim_id:claim.id,p_proposed_value:{value:value||null},p_proof:proof,p_notes:notes[claim.id]?.trim()||null});if(error)throw error;toast.success("Proof submitted for review.");await queryClient.invalidateQueries({queryKey:["my-enrichment-claims"]});}catch(e:any){toast.error(e.message)}finally{setBusy(null)}};
  if(!user)return <main className="mx-auto max-w-3xl px-4 py-16 text-center"><Compass className="mx-auto h-10 w-10 text-primary"/><h1 className="mt-4 font-serif text-4xl font-bold">Sign in to Scout.</h1><Button asChild className="mt-6"><Link to="/auth?next=/scout/enrichment">Sign in</Link></Button></main>;
  return <main className="mx-auto min-h-screen max-w-6xl px-4 py-12"><p className="text-xs font-black uppercase tracking-[.24em] text-primary">{t("scoutEnrich.badge")}</p><h1 className="mt-3 font-serif text-5xl font-bold">{t("scoutEnrich.title")}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{t("scoutEnrich.subtitle")}</p>
    <div className="mt-8 grid gap-4 sm:grid-cols-3">{[[t("scoutEnrich.active"),groups.active.length,Clock3],[t("scoutEnrich.inReview"),groups.review.length,Send],[t("scoutEnrich.decided"),groups.complete.length,CheckCircle2]].map(([label,count,Icon]:any)=><div key={label} className="rounded-2xl border border-border bg-card p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-3 text-3xl font-bold">{count}</p><p className="text-sm text-muted-foreground">{label}</p></div>)}</div>
    <section className="mt-10 space-y-4">{query.isLoading?<Loader2 className="h-6 w-6 animate-spin"/>:groups.active.map(claim=><article key={claim.id} className="rounded-3xl border border-primary/20 bg-card p-6"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><Badge variant="outline">{claim.field_key.replace(/_/g," ")}</Badge><h2 className="mt-3 text-2xl font-bold">{claim.title}</h2><Link to={`/venues/${claim.venue_slug}`} className="text-sm text-primary hover:underline">{claim.venue_name} · {claim.city}</Link><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{claim.instructions}</p></div><div className="text-right"><p className="text-sm font-bold text-amber-500">{claim.reward_points} points eligible</p><p className="mt-1 text-xs text-muted-foreground">Expires {new Date(claim.expires_at).toLocaleString()}</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-2"><Input value={values[claim.id]||""} onChange={e=>setValues(v=>({...v,[claim.id]:e.target.value}))} placeholder="Verified value, URL, address, phone, or observation"/><label className="flex h-10 cursor-pointer items-center justify-center gap-2 rounded-md border border-border bg-background text-sm font-medium"><Upload className="h-4 w-4"/>{files[claim.id]?.name||"Attach proof"}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFiles(v=>({...v,[claim.id]:e.target.files?.[0]||null}))}/></label><Textarea className="md:col-span-2" value={notes[claim.id]||""} onChange={e=>setNotes(v=>({...v,[claim.id]:e.target.value}))} placeholder="What did you observe, and when?"/><Button className="md:col-span-2" disabled={busy===claim.id||uploading} onClick={()=>submit(claim)}>{busy===claim.id?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Camera className="mr-2 h-4 w-4"/>}{t("scoutEnrich.submitProof")}</Button></div></article>)}{!query.isLoading&&!groups.active.length?<div className="rounded-3xl border border-dashed border-border p-10 text-center"><h2 className="text-xl font-bold">{t("scoutEnrich.noAssignments")}</h2><Button asChild variant="outline" className="mt-4"><Link to="/discover/venues">{t("scoutEnrich.findPlace")}</Link></Button></div>:null}</section>
    {(groups.review.length||groups.complete.length)?<section className="mt-12"><h2 className="font-serif text-3xl font-bold">{t("scoutEnrich.history")}</h2><div className="mt-4 space-y-3">{[...groups.review,...groups.complete].map(c=><div key={c.id} className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{c.title} · {c.venue_name}</p><p className="text-sm text-muted-foreground">{c.reviewer_notes||"Awaiting operator review"}</p></div><div className="flex items-center gap-2"><Badge>{c.status}</Badge>{c.status==="approved"?<span className="text-sm font-bold text-emerald-500">+{c.reward_points_awarded} pts · +{c.reputation_delta} rep</span>:null}</div></div>)}</div></section>:null}</main>;
}
