import type { MomentProps, SceneProps } from '@/components/radar/types';

export const CURATED_KINGSTON_SCENES: SceneProps[] = [
  {
    id: '00000000-0000-0000-0001-000000000001',
    slug: 'kingston-after-dark',
    name: 'Kingston After Dark',
    description: 'The definitive lens for nightlife, late-night food spots, live music, and party culture in Kingston.',
    category: 'Nightlife & Music',
    coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800',
    activeMomentsCount: 12,
    activeDiscoveriesCount: 4,
    activeParticipantsCount: 1420,
    creatorsCount: 8,
    isJoined: true
  },
  {
    id: '00000000-0000-0000-0001-000000000002',
    slug: 'food-and-taste',
    name: 'Food & Taste Jamaica',
    description: 'Discover underrated breakfast joints, street vendors, chef popups, and signature dining experiences across the island.',
    category: 'Food & Dining',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=800',
    activeMomentsCount: 15,
    activeDiscoveriesCount: 9,
    activeParticipantsCount: 1280,
    creatorsCount: 16,
    isJoined: false
  },
  {
    id: '00000000-0000-0000-0001-000000000003',
    slug: 'move-jamaica',
    name: 'Move & Fitness Jamaica',
    description: 'Active lifestyle, outdoor runs, fitness popups, wellness retreats, and beach workouts from Kingston to Negril.',
    category: 'Fitness & Health',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800',
    activeMomentsCount: 8,
    activeDiscoveriesCount: 5,
    activeParticipantsCount: 620,
    creatorsCount: 6,
    isJoined: false
  }
];

export const CURATED_KINGSTON_MOMENTS: MomentProps[] = [
  // --- PRICE SMART & EDITORIAL PROMOTIONS ---
  {
    id: '00000000-0000-0000-0002-000000000060',
    title: 'Arla Whip & Cook @ PriceSmart: Taste It. Whip It. Cook It.',
    description: 'Experience Arla Pro Whip & Cook 28% live at PriceSmart Jamaica (111 Red Hills Rd). Taste savoury Rasta Pasta vs cold Chocolate Chip Mousse, pick your winner in the live Taste-Off, unlock the 5-Recipe Pack, and get 1L cartons for approx. J$1,200 during the roadshow (regular price approx. J$2,700).',
    intentType: 'TRY',
    ownership: 'PROMORANG PRESENTS',
    venueName: 'PriceSmart Jamaica (Red Hills Road)',
    location: '111 Red Hills Road, Kingston 19, Jamaica',
    dateDisplay: 'Daily 10:00 AM – 8:00 PM (This Week Only)',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 100,
    subMomentsCount: 5,
    attendeesCount: 340,
    pointsReward: 150,
    isClaimed: true
  },

  // --- OCHO RIOS & ST. ANN ---
  {
    id: '00000000-0000-0000-0002-000000000051',
    title: 'Sophisticated — The Summer End Beach Party',
    description: "Presented by Midas Entertainment & 8Rivaz Ultra Lounge. The ultimate summer finale beach party at Plantation Cove, St. Ann featuring Vanessa Bling live in concert, alongside Illusion Sound, Trippple X, Bishop Escobar, and Fyah Prince. Hosted drinks 4:00 PM – 7:00 PM. Admission: J$5,000 Pre-sold | J$6,000 at Gate.",
    intentType: 'ATTEND',
    ownership: 'PROMORANG PRESENTS',
    venueName: 'Plantation Cove',
    location: 'Plantation Cove, Priory, St. Ann, Jamaica',
    dateDisplay: 'Saturday, August 29, 2026 • 4:00 PM – 10:00 PM',
    image: '/events/sophisticated-flyer.jpg',
    promoKeysAvailable: 50,
    subMomentsCount: 4,
    attendeesCount: 0,
    pointsReward: 200,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000052',
    title: 'Capleton Encore Live — Culture Rising',
    description: "Presented by Midas Entertainment & 8Rivaz Ultra Lounge. The high-energy live reggae concert at Plantation Cove, St. Ann headlined by Capleton ('The Fireman' / King Shango), featuring Nesbeth and Dean Fraser, with entertainment by DJ Delano (Renaissance), Bass Odyssey, and DJ Rors. Admission: J$5,000 Pre-sold | J$7,000 at Gate.",
    intentType: 'ATTEND',
    ownership: 'PROMORANG PRESENTS',
    venueName: 'Plantation Cove',
    location: 'Plantation Cove, Priory, St. Ann, Jamaica',
    dateDisplay: 'Sunday, August 30, 2026 • 4:00 PM – 10:00 PM',
    image: '/events/encore-live-capleton-flyer.jpg',
    promoKeysAvailable: 50,
    subMomentsCount: 4,
    attendeesCount: 0,
    pointsReward: 200,
    isClaimed: false
  },

  // --- MONTEGO BAY (ST. JAMES) ---
  {
    id: '00000000-0000-0000-0002-000000000071',
    title: 'Pier 1 Seafood & Reggae Sunset Sessions',
    description: "Montego Bay’s premier open-air waterfront dining and nightlife venue overlooking the bay. Feast on grilled lobster, garlic shrimp, and fresh escovitch fish while listening to live acoustic reggae and resident DJs at sunset.",
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Pier 1 on the Waterfront',
    location: 'Howard Cooke Blvd, Montego Bay, St. James',
    dateDisplay: 'Every Friday & Sunday from 5:00 PM',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 15,
    subMomentsCount: 3,
    attendeesCount: 280,
    pointsReward: 150,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000072',
    title: "Doctor's Cave Beach Club Crystal Waters & Snorkel Lyme",
    description: "Spend the day on the world-renowned white sands of Doctor's Cave on the Hip Strip. Dive into crystal clear feeding reefs, chill with tropical cocktails in beachside cabanas, and collect your verified beach pass perk.",
    intentType: 'CONNECT',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Doctor's Cave Beach Club",
    location: 'Gloucester Ave (Hip Strip), Montego Bay',
    dateDisplay: 'Daily 8:30 AM – 5:30 PM',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 20,
    subMomentsCount: 2,
    attendeesCount: 310,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000073',
    title: 'Rose Hall Great House Night Candlelight & Rum Tour',
    description: "Explore the legendary 18th-century Jamaican estate by candlelight. Uncover the tale of Annie Palmer (The White Witch of Rose Hall), visit the historic sugar dungeon pub, and sample aged Jamaican rum.",
    intentType: 'LEARN',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Rose Hall Great House',
    location: 'Rose Hall Highway, Montego Bay',
    dateDisplay: 'Nightly 6:30 PM – 9:00 PM',
    image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 12,
    subMomentsCount: 3,
    attendeesCount: 175,
    pointsReward: 150,
    isClaimed: false
  },

  // --- NEGRIL (WESTMORELAND & HANOVER) ---
  {
    id: '00000000-0000-0000-0002-000000000081',
    title: "Rick's Cafe Sunset Watch & Cliff Jump Showcase",
    description: "The global icon on the cliffs of Negril's West End. Watch breathtaking 35-foot cliff divers plunge into turquoise waters against world-famous Caribbean sunsets, backed by high-energy live bands and tropical rum punch.",
    intentType: 'ATTEND',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Rick's Cafe Negril",
    location: 'West End Cliffs, Negril, Westmoreland',
    dateDisplay: 'Daily from 2:00 PM – 8:30 PM (Peak Sunset)',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 25,
    subMomentsCount: 4,
    attendeesCount: 520,
    pointsReward: 200,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000082',
    title: 'Roots Bamboo Barefoot Beach Reggae Night',
    description: "Seven Mile Beach live roots and dancehall concert on the sand. Dance under coconut palms by beach bonfires with top live reggae acts and icy Red Stripe.",
    intentType: 'ATTEND',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Roots Bamboo Beach Lounge',
    location: 'Norman Manley Blvd, Seven Mile Beach, Negril',
    dateDisplay: 'Every Wednesday & Sunday at 9:00 PM',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 15,
    subMomentsCount: 3,
    attendeesCount: 260,
    pointsReward: 150,
    isClaimed: false
  },

  // --- PORT ANTONIO (PORTLAND) ---
  {
    id: '00000000-0000-0000-0002-000000000091',
    title: 'Boston Bay Authentic Pit Jerk Feast & Surf Lyme',
    description: "Journey to the birthplace of Jamaican jerk seasoning. Savor authentic pork and chicken slow-roasted over pimento wood logs, freshly made festivals, and enjoy the surf break at Boston Bay beach.",
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Boston Jerk Cultural Centre',
    location: 'Boston Bay, Portland, Jamaica',
    dateDisplay: 'Daily 11:00 AM – 7:00 PM',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 20,
    subMomentsCount: 3,
    attendeesCount: 290,
    pointsReward: 150,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000092',
    title: "Frenchman's Cove River Meets Ocean Luxury Day Pass",
    description: "One of the most breathtaking private coves in the world. Float down the ice-cold freshwater emerald river right into the warm Caribbean sea surrounded by lush hanging vines and white sands.",
    intentType: 'CONNECT',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Frenchman's Cove Beach & River",
    location: 'San San Estate, Port Antonio, Portland',
    dateDisplay: 'Daily 9:00 AM – 5:00 PM',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 10,
    subMomentsCount: 2,
    attendeesCount: 185,
    pointsReward: 150,
    isClaimed: false
  },

  // --- SOUTH COAST (ST. ELIZABETH & MANCHESTER) ---
  {
    id: '00000000-0000-0000-0002-000000000101',
    title: "Floyd's Pelican Bar Stilted Sandbar Experience",
    description: "Hop on a wooden fishing boat 1 mile off the coast of Parottee to visit the rustic driftwood bar built on stilts on a shallow sandbar. Carve your name into the wood, drink cold beers, and eat freshly caught fried fish in the ocean.",
    intentType: 'CONNECT',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Floyd's Pelican Bar",
    location: 'Parottee Bay, St. Elizabeth, Jamaica',
    dateDisplay: 'Daily 10:00 AM – Sunset',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 15,
    subMomentsCount: 3,
    attendeesCount: 320,
    pointsReward: 200,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000102',
    title: "Jakes Treasure Beach Farm-to-Table Sunset Dinner",
    description: "Bohemian south coast sanctuary celebrating local organic agriculture, freshly caught seafood, and warm community vibes on the dark-sand coastline of Calabash Bay.",
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Jakes Hotel & Dougie's Bar",
    location: 'Calabash Bay, Treasure Beach, St. Elizabeth',
    dateDisplay: 'Thursdays – Sundays from 5:30 PM',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 10,
    subMomentsCount: 2,
    attendeesCount: 140,
    pointsReward: 150,
    isClaimed: false
  },

  // --- PORTMORE (ST. CATHERINE) ---
  {
    id: '00000000-0000-0000-0002-000000000111',
    title: 'Hellshire Beach Fried Fish & Bammy Sunday Ritual',
    description: "The quintessential Jamaican weekend ritual. Freshly caught snapper, parrotfish, and lobster fried to order, served with hot festival and steamed bammy right on the beach with cold drinks and reggae sounds.",
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Hellshire Beach Seafood Village',
    location: 'Hellshire Beach, Portmore, St. Catherine',
    dateDisplay: 'Sundays & Weekends 11:00 AM – 8:00 PM',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 25,
    subMomentsCount: 3,
    attendeesCount: 450,
    pointsReward: 100,
    isClaimed: false
  },

  // --- KINGSTON & ST. ANDREW ---
  {
    id: '00000000-0000-0000-0002-000000000001',
    title: 'I Luv Hip Hop Live Culture Lab',
    description: "Kingston’s premier hip hop and sound system lab at Fiction. Vote on the sound of the night, discover the next selector, and earn your way inside the DJ booth with your crew.",
    intentType: 'ATTEND',
    ownership: 'PROMORANG PRESENTS',
    venueName: 'Fiction Nightclub',
    location: 'Marketplace, Constant Spring Rd, Kingston',
    dateDisplay: 'Every Wednesday from 10:00 PM',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 8,
    subMomentsCount: 3,
    attendeesCount: 142,
    pointsReward: 120,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000002',
    title: 'Fiction Saturday Ultra VIP Experience',
    description: 'High-energy nightclubbing in the heart of Kingston. Premium bottle service, guest international DJs, and exclusive access to the VIP Mezzanine.',
    intentType: 'ATTEND',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Fiction Nightclub',
    location: 'Marketplace, Constant Spring Rd, Kingston',
    dateDisplay: 'Every Saturday from 10:30 PM',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 5,
    subMomentsCount: 2,
    attendeesCount: 220,
    pointsReward: 150,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000025',
    title: "Usain Bolt's Tracks & Records Live Music & Grill",
    description: 'The definitive sports and reggae culture hub celebrating Jamaican athletic excellence, authentic jerk platters, and weekly live music sessions.',
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Tracks & Records Marketplace",
    location: '67 Constant Spring Rd, Kingston',
    dateDisplay: 'Every Tuesday & Friday from 7:00 PM',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 10,
    subMomentsCount: 3,
    attendeesCount: 180,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000026',
    title: 'Verandah Dining & Live Jazz at Steakhouse',
    description: 'Colonial heritage fine dining on the historic Devon House verandah featuring premium dry-aged steaks, Caribbean lobster, and live jazz.',
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'The Steakhouse on the Verandah',
    location: 'Devon House, 26 Hope Rd, Kingston',
    dateDisplay: 'Every Friday from 9:00 PM',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 8,
    subMomentsCount: 3,
    attendeesCount: 340,
    pointsReward: 150,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000022',
    title: 'Tacos, Margaritas & Patio Beats at Tacbar',
    description: 'Devon House courtyard street taco hub blending authentic Mexican barbacoa and carnitas with spicy Jamaican Scotch bonnet flare.',
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Tacbar Jamaica (Devon House)',
    location: '26 Hope Rd, Devon House Courtyard',
    dateDisplay: 'Taco Tuesday & Daily 1:00 PM – Midnight',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 6,
    subMomentsCount: 3,
    attendeesCount: 195,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000023',
    title: "Let's Lyme Friday Poolside & Grill at Pegasus",
    description: 'Premier New Kingston weekend kickoff at the Pegasus tropical pool lounge with live acoustic entertainment and barbecue grill stations.',
    intentType: 'CONNECT',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'The Jamaica Pegasus Hotel (Pool Lounge)',
    location: '81 Knutsford Blvd, New Kingston',
    dateDisplay: 'Every Friday from 6:00 PM',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 5,
    subMomentsCount: 3,
    attendeesCount: 210,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000017',
    title: 'Tacos & Reggae Jam at Chilitos JaMexican',
    description: 'Lively courtyard fiesta blending authentic Mexican tacos, burritos, and tequila cocktails with bold Jamaican spices.',
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Chilitos JaMexican',
    location: '88 Hope Rd, Kingston 6',
    dateDisplay: 'Taco Tuesday & Weekends from 12:00 PM',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 4,
    subMomentsCount: 3,
    attendeesCount: 142,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000018',
    title: 'AC Lounge Tapas & Craft Mixology Evenings',
    description: 'Chic European-inspired lounge with Spanish tapas, signature rum cocktails, and cosmopolitan weekend DJ sets.',
    intentType: 'CONNECT',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'AC Lounge (AC Hotel Kingston)',
    location: '38-42 Lady Musgrave Rd, Kingston',
    dateDisplay: 'Thursdays – Saturdays from 6:00 PM',
    image: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 5,
    subMomentsCount: 2,
    attendeesCount: 160,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000004',
    title: 'Kingston Dub Club Sunday Roots Session',
    description: 'Legendary weekly hilltop sound system gathering overlooking city lights. Authentic dub plates and strictly conscious vibes.',
    intentType: 'ATTEND',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Kingston Dub Club',
    location: "Skyline Drive, Jack's Hill",
    dateDisplay: 'Every Sunday at 8:00 PM',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 12,
    subMomentsCount: 3,
    attendeesCount: 215,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000005',
    title: 'Devon House Gourmet Bakery & Ice Cream Crawl',
    description: 'Historic estate culinary exploration featuring world-famous gourmet patties and authentic Devon House I Scream.',
    intentType: 'TRY',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Devon House Gourmet Court',
    location: 'Hope Rd, Kingston',
    dateDisplay: 'Daily 10:00 AM – 9:00 PM',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 8,
    subMomentsCount: 4,
    attendeesCount: 148,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000006',
    title: "Live Acoustic & Grill at Janga's",
    description: 'Relaxed open-air courtyard sessions with acoustic live bands, craft cocktails, and authentic Jamaican grilled bites.',
    intentType: 'CONNECT',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: "Janga's Soundbar & Grill",
    location: 'Belmont Rd, New Kingston',
    dateDisplay: 'Every Thursday at 7:30 PM',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 6,
    subMomentsCount: 2,
    attendeesCount: 88,
    pointsReward: 100,
    isClaimed: false
  },
  {
    id: '00000000-0000-0000-0002-000000000015',
    title: 'Downtown Kingston Creative Artwalk & Mural Tour',
    description: 'Free public cultural festival celebrating street murals, live performances, local crafts, and historic lane tours.',
    intentType: 'LEARN',
    ownership: 'EDITORIAL DISCOVERY',
    venueName: 'Downtown Art District',
    location: 'Water Lane & Church St, Downtown KGN',
    dateDisplay: 'Last Sunday of Month 11:00 AM – 6:00 PM',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=800',
    promoKeysAvailable: 15,
    subMomentsCount: 4,
    attendeesCount: 245,
    pointsReward: 150,
    isClaimed: false
  }
];
